// Code generated by packages/memini-client. DO NOT EDIT.
//
// Regenerate with:  mise run build-client
// CI fails on drift via:  mise run client-check
//
// Source of truth: packages/memini-client/src/*.ts
// This file is committed because the plugin ships as raw files with no
// install-time build step — the hooks run under a bare `node`.

// src/redact.ts
var SENSITIVE = /(^|_)(KEY|TOKEN|SECRET|PASSWORD|PASS|BEARER|DSN|CREDENTIALS?)$/i;
function isSensitive(name) {
  return SENSITIVE.test(name);
}
function redactValue(value) {
  if (!value) return "";
  if (value.length <= 12) return "***";
  return `${value.slice(0, 3)}\u2026${value.slice(-4)}`;
}
function redactByName(name, value) {
  return isSensitive(name) ? redactValue(value) : value;
}

// src/namespace-validate.ts
var MAX_NAMESPACE_BYTES = 256;
function normalizeNamespace(ns) {
  let out = String(ns ?? "").trim();
  out = out.replace(/^\/+|\/+$/g, "");
  while (out.includes("//")) out = out.replace(/\/\/+/g, "/");
  return out;
}
function validateNamespace(ns) {
  if (!ns) return "namespace is empty";
  if (Buffer.byteLength(ns, "utf8") > MAX_NAMESPACE_BYTES) {
    return `namespace exceeds ${MAX_NAMESPACE_BYTES} bytes`;
  }
  if (/[\r\n]/.test(ns)) return "namespace contains a newline";
  if (/[\x00-\x1F\x7F]/.test(ns)) return "namespace contains a control character";
  if (/[^\x20-\x7E]/.test(ns)) return "namespace contains a non-ASCII character";
  return null;
}

// src/capture.ts
var TRUNCATION_MARKER = "\n[...truncated]";
function truncateForCapture(s, max) {
  if (typeof max !== "number" || !Number.isFinite(max) || max <= 0) return s;
  const cap = Math.floor(max);
  if (s.length <= cap) return s;
  let i = 0;
  for (let n = 0; i < s.length && n < cap; n++) {
    i += s.codePointAt(i) > 65535 ? 2 : 1;
  }
  if (i >= s.length) return s;
  return s.slice(0, i) + TRUNCATION_MARKER;
}
function buildTurnCapture(userText, assistantText, userMax, assistantMax) {
  return `${truncateForCapture(userText, userMax)}

${truncateForCapture(assistantText, assistantMax)}`;
}

// src/override.ts
import { execSync } from "node:child_process";
import { homedir } from "node:os";
import fs from "node:fs";
import path from "node:path";
var OVERRIDES_VERSION = 1;
var EMPTY = { version: OVERRIDES_VERSION, overrides: {} };
function defaultOverridesPath(env = process.env) {
  const xdg = env["XDG_CONFIG_HOME"];
  const base = xdg && xdg.trim() ? xdg : path.join(homedir(), ".config");
  return path.join(base, "memini", "overrides.json");
}
function overrideKey(cwd) {
  const dir = cwd && cwd.trim() ? cwd : process.cwd();
  try {
    const top = execSync("git rev-parse --show-toplevel", {
      cwd: dir,
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 500
    }).toString().trim();
    if (top) return path.resolve(top);
  } catch {
  }
  return path.resolve(dir);
}
function readOverrides(opts = {}) {
  const p = opts.overridesPath || defaultOverridesPath(opts.env);
  try {
    const parsed = JSON.parse(fs.readFileSync(p, "utf8"));
    if (!parsed || typeof parsed !== "object" || typeof parsed.overrides !== "object") {
      return { ...EMPTY, overrides: {} };
    }
    return {
      version: typeof parsed.version === "number" ? parsed.version : OVERRIDES_VERSION,
      overrides: parsed.overrides || {}
    };
  } catch {
    return { ...EMPTY, overrides: {} };
  }
}
function readOverride(cwd, opts = {}) {
  const file = readOverrides(opts);
  const keys = Object.keys(file.overrides);
  if (keys.length === 0) return void 0;
  const entry = file.overrides[overrideKey(cwd)];
  if (!entry || typeof entry.namespace !== "string" || !entry.namespace.trim()) return void 0;
  return entry;
}

// src/session.ts
import { execFileSync } from "node:child_process";
import { homedir as homedir2, tmpdir } from "node:os";
import fs2 from "node:fs";
import path2 from "node:path";
function cacheDir(env = process.env) {
  const base = env["XDG_CACHE_HOME"] || path2.join(homedir2() || tmpdir(), ".cache");
  return path2.join(base, "memini");
}
function sessionCwdPath(ppid, env = process.env) {
  return path2.join(cacheDir(env), "sessions", `pid-${ppid}.cwd`);
}
var SESSION_CWD_TTL_MS = 6 * 60 * 60 * 1e3;
function writeSessionCwd(ppid, cwd, env = process.env, now = Date.now()) {
  if (!ppid || !cwd || !cwd.trim()) return;
  try {
    const p = sessionCwdPath(ppid, env);
    fs2.mkdirSync(path2.dirname(p), { recursive: true });
    const rec = { cwd: path2.resolve(cwd), writtenAt: now };
    fs2.writeFileSync(p, JSON.stringify(rec));
  } catch {
  }
}
function readSessionCwd(ppid, env = process.env, now = Date.now()) {
  try {
    const raw = fs2.readFileSync(sessionCwdPath(ppid, env), "utf8").trim();
    if (!raw) return void 0;
    const rec = JSON.parse(raw);
    if (!rec || typeof rec.cwd !== "string" || !rec.cwd) return void 0;
    if (typeof rec.writtenAt !== "number" || !Number.isFinite(rec.writtenAt)) return void 0;
    const age = now - rec.writtenAt;
    if (age < 0 || age > SESSION_CWD_TTL_MS) return void 0;
    return fs2.existsSync(rec.cwd) ? rec.cwd : void 0;
  } catch {
    return void 0;
  }
}
function deleteSessionCwd(ppid, env = process.env) {
  if (!ppid) return;
  try {
    fs2.rmSync(sessionCwdPath(ppid, env), { force: true });
  } catch {
  }
}
function processCwd(pid) {
  if (!pid || pid <= 1) return void 0;
  try {
    const link = fs2.readlinkSync(`/proc/${pid}/cwd`);
    if (link && fs2.existsSync(link)) return link;
  } catch {
  }
  if (process.platform === "darwin") {
    try {
      const out = execFileSync("lsof", ["-a", "-d", "cwd", "-p", String(pid), "-Fn"], {
        stdio: ["ignore", "pipe", "ignore"],
        timeout: 1e3
      }).toString();
      for (const line of out.split("\n")) {
        if (line.startsWith("n/")) {
          const p = line.slice(1).trim();
          if (p && fs2.existsSync(p)) return p;
        }
      }
    } catch {
    }
  }
  return void 0;
}
function looksLikePluginRoot(dir, env = process.env) {
  if (!dir) return true;
  const d = path2.resolve(dir);
  const pluginRoot = env["CLAUDE_PLUGIN_ROOT"];
  if (pluginRoot && path2.resolve(pluginRoot) === d) return true;
  return /[/\\](plugins?)[/\\]cache[/\\]/.test(d);
}
function resolveHarnessCwd(env = process.env, ppid = process.ppid) {
  const explicit = env["CLAUDE_PROJECT_DIR"];
  if (explicit && explicit.trim() && !looksLikePluginRoot(explicit, env)) {
    return { cwd: path2.resolve(explicit.trim()), source: "CLAUDE_PROJECT_DIR" };
  }
  const parent = processCwd(ppid);
  if (parent && !looksLikePluginRoot(parent, env)) {
    return { cwd: parent, source: "parent-process" };
  }
  const recorded = readSessionCwd(ppid, env);
  if (recorded && !looksLikePluginRoot(recorded, env)) {
    return { cwd: recorded, source: "session-file" };
  }
  return void 0;
}

// src/bootstrap.ts
var DEFAULT_TIMEOUT_MS = 3e4;
var MIN_TIMEOUT_MS = 100;
var LOOPBACK_HOSTS = /* @__PURE__ */ new Set(["localhost", "127.0.0.1", "::1"]);
function envTimeoutMs(raw, fallback = DEFAULT_TIMEOUT_MS) {
  if (raw == null || raw.trim() === "") return fallback;
  const n = Number(raw.trim());
  if (!Number.isFinite(n)) return fallback;
  return Math.max(MIN_TIMEOUT_MS, Math.trunc(n));
}
function envEnabled(raw, defaultOn) {
  if (raw == null || raw === "") return defaultOn;
  return !/^(0|false|no|off)$/i.test(raw.trim());
}
function readBootstrap(env = process.env) {
  return {
    baseUrl: env["MEMINI_BASE_URL"] || "http://localhost:8080",
    apiKey: env["MEMINI_API_KEY"] || "",
    requireHttps: envEnabled(env["MEMINI_REQUIRE_HTTPS"], false),
    debug: envEnabled(env["MEMINI_DEBUG"], false),
    agent: env["MEMINI_AGENT"] || "",
    namespaceEnv: (env["MEMINI_NAMESPACE"] || "").trim(),
    namespacePrefixEnv: (env["MEMINI_NAMESPACE_PREFIX"] || "").trim(),
    homeEnv: (env["MEMINI_HOME"] || "").trim(),
    timeoutMs: envTimeoutMs(env["MEMINI_TIMEOUT_MS"])
  };
}
function isPlaintextBearerUnsafe(baseUrl, secret) {
  if (!secret) return false;
  try {
    const u = new URL(baseUrl);
    return u.protocol === "http:" && !LOOPBACK_HOSTS.has(u.hostname.replace(/^\[|\]$/g, "").toLowerCase());
  } catch {
    return false;
  }
}
function assertBearerTransportSafe(baseUrl, secret, env = process.env) {
  if (!isPlaintextBearerUnsafe(baseUrl, secret)) return;
  if (!envEnabled(env["MEMINI_REQUIRE_HTTPS"], false)) return;
  throw new Error(
    `memini: a bearer token is configured for plaintext HTTP to ${baseUrl}. The token and memory payloads can be observed on the network; use HTTPS or an SSH tunnel.`
  );
}

// src/settings.ts
var BEHAVIOR_KNOBS = [
  { envName: "MEMINI_CAPTURE_TURNS", wireKey: "capture_turns", kind: "bool", default: true },
  { envName: "MEMINI_SESSION_DIGEST", wireKey: "session_digest", kind: "bool", default: true },
  { envName: "MEMINI_INLINE_EXTRACT", wireKey: "inline_extract", kind: "bool", default: true },
  { envName: "MEMINI_AUTO_SAVE", wireKey: "auto_save", kind: "bool", default: true },
  { envName: "MEMINI_AUTO_SAVE_INTERVAL", wireKey: "auto_save_interval", kind: "int", default: 10 },
  { envName: "MEMINI_AUTO_SAVE_MIN_EVENTS", wireKey: "auto_save_min_events", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_BRIEFING_PINNED", wireKey: "inject_briefing_pinned", kind: "int", default: 5 },
  { envName: "MEMINI_INJECT_BRIEFING_FACTS", wireKey: "inject_briefing_facts", kind: "int", default: 5 },
  { envName: "MEMINI_INJECT_BRIEFING_PROCEDURES", wireKey: "inject_briefing_procedures", kind: "int", default: 5 },
  { envName: "MEMINI_INJECT_BRIEFING_RECENT", wireKey: "inject_briefing_recent", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_BRIEFING_MAX_TOK", wireKey: "inject_briefing_max_tok", kind: "int", default: 600 },
  { envName: "MEMINI_INJECT_PRETOOL_ITEMS", wireKey: "inject_pretool_items", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_PRETOOL_MAX_TOK", wireKey: "inject_pretool_max_tok", kind: "int", default: 200 },
  { envName: "MEMINI_INJECT_PRETOOL_MIN_SCORE", wireKey: "inject_pretool_min_score", kind: "float", default: 0 },
  {
    envName: "MEMINI_INJECT_PRETOOL_TOOLS",
    wireKey: "inject_pretool_tools",
    kind: "list",
    default: ["Read", "Write", "Edit", "MultiEdit", "Glob", "Grep"]
  },
  { envName: "MEMINI_INJECT_PRETOOL_GATE_MS", wireKey: "inject_pretool_gate_ms", kind: "int", default: 9e4 },
  { envName: "MEMINI_INJECT_DEDUPE", wireKey: "inject_dedupe", kind: "bool", default: true },
  { envName: "MEMINI_INJECT_TELEMETRY", wireKey: "inject_telemetry", kind: "bool", default: true },
  { envName: "MEMINI_INJECT_COOLDOWN_MS", wireKey: "inject_cooldown_ms", kind: "int", default: 18e5 },
  { envName: "MEMINI_INJECT_COOLDOWN_PROMPTS", wireKey: "inject_cooldown_prompts", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_LABELS", wireKey: "inject_labels", kind: "list", default: [] },
  { envName: "MEMINI_RECALL", wireKey: "recall", kind: "bool", default: true },
  { envName: "MEMINI_CAPTURE", wireKey: "capture", kind: "bool", default: true },
  { envName: "MEMINI_RECALL_LIMIT", wireKey: "recall_limit", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_RECALL_MAX_TOK", wireKey: "inject_recall_max_tok", kind: "int", default: 250 },
  { envName: "MEMINI_INJECT_RECALL_MIN_SCORE", wireKey: "inject_recall_min_score", kind: "float", default: 0 },
  { envName: "MEMINI_MIN_CAPTURE_CHARS", wireKey: "min_capture_chars", kind: "int", default: 0 },
  { envName: "MEMINI_CAPTURE_USER_MAX_CHARS", wireKey: "capture_user_max_chars", kind: "int", default: 1e3 },
  {
    envName: "MEMINI_CAPTURE_ASSISTANT_MAX_CHARS",
    wireKey: "capture_assistant_max_chars",
    kind: "int",
    default: 3e3
  },
  // Also read at the transport layer (bootstrap.ts's timeoutMs), because a
  // request timeout has to exist before the handshake that fetches settings.
  // Both spellings share DEFAULT_TIMEOUT_MS/MIN_TIMEOUT_MS, so there is exactly
  // one number: raising it here (server-side) or in the env both work.
  {
    envName: "MEMINI_TIMEOUT_MS",
    wireKey: "request_timeout_ms",
    kind: "int",
    default: DEFAULT_TIMEOUT_MS,
    min: MIN_TIMEOUT_MS
  }
];
function parseIntKnob(raw, fallback, min = 0) {
  const n = Number.parseInt(raw, 10);
  if (!Number.isFinite(n) || n < 0) return fallback;
  return Math.max(min, n);
}
function parseFloatKnob(raw, fallback) {
  const n = Number.parseFloat(raw);
  return Number.isFinite(n) && n >= 0 ? n : fallback;
}
function parseListKnob(raw) {
  return raw.split(/[|,]/).map((s) => s.trim().toLowerCase()).filter(Boolean);
}
function effectiveSetting(knob, server, env = process.env) {
  const raw = env[knob.envName];
  if (raw != null && raw !== "") {
    let value;
    switch (knob.kind) {
      case "bool":
        value = !/^(0|false|no|off)$/i.test(raw.trim());
        break;
      case "int":
        value = parseIntKnob(raw, knob.default, knob.min);
        break;
      case "float":
        value = parseFloatKnob(raw, knob.default);
        break;
      case "list":
        value = parseListKnob(raw);
        break;
    }
    return { value, source: "env-override" };
  }
  if (server && Object.prototype.hasOwnProperty.call(server, knob.wireKey)) {
    return { value: server[knob.wireKey], source: "server" };
  }
  return { value: knob.default, source: "default" };
}

// src/facts.ts
import { execFileSync as execFileSync2 } from "node:child_process";
import path3 from "node:path";
import crypto from "node:crypto";
function gitOut(args, dir) {
  try {
    const out = execFileSync2("git", args, {
      cwd: dir,
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 500
    }).toString().trim();
    return out || void 0;
  } catch {
    return void 0;
  }
}
function gatherFacts(cwd, env = process.env) {
  const dir = cwd && cwd.trim() ? cwd : process.cwd();
  const facts = {
    cwd_basename: path3.basename(dir)
  };
  const remote = gitOut(["remote", "get-url", "origin"], dir);
  if (remote) facts.remote_url = remote;
  const toplevel = gitOut(["rev-parse", "--show-toplevel"], dir);
  if (toplevel) {
    facts.toplevel_path = toplevel;
    facts.toplevel_basename = path3.basename(toplevel);
  }
  const agent = env["MEMINI_AGENT"];
  if (agent) facts.agent = agent;
  const ns = (env["MEMINI_NAMESPACE"] || "").trim();
  if (ns) facts.env_namespace = ns;
  const prefix = (env["MEMINI_NAMESPACE_PREFIX"] || "").trim();
  if (prefix) facts.env_namespace_prefix = prefix;
  return facts;
}
function factsFingerprint(f) {
  const rec = f;
  const keys = Object.keys(f).filter((k) => rec[k] !== void 0).sort();
  const parts = keys.map((k) => `${k}=${rec[k]}`);
  return crypto.createHash("sha256").update(parts.join("\n"), "utf8").digest("hex").slice(0, 16);
}

// src/resolve.ts
function remotePathSegments(url) {
  if (typeof url !== "string" || !url) return [];
  const cleaned = url.trim().replace(/\/+$/, "").replace(/\.git$/i, "");
  if (!cleaned) return [];
  const scpMatch = cleaned.match(/^[^/:]+:[^/]/);
  const p = scpMatch ? cleaned.slice(scpMatch[0].indexOf(":") + 1) : cleaned;
  return p.split("/").filter(Boolean);
}
function repoNameFromRemote(url) {
  const segs = remotePathSegments(url);
  return segs.length ? segs[segs.length - 1] : void 0;
}
function repoSlugFromRemote(url) {
  const segs = remotePathSegments(url);
  if (!segs.length) return void 0;
  if (segs.length === 1) return segs[0];
  const owner = segs[segs.length - 2].replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
  const repo = segs[segs.length - 1];
  return owner ? `${owner}-${repo}` : repo;
}
function withAgent(ns, agent) {
  const trimmed = (agent || "").trim();
  if (!trimmed) return ns;
  const seg = trimmed.replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
  return seg ? `${ns}/${seg}` : ns;
}
function deriveLocalNamespace(f, scope = "repo") {
  if (f.declared_namespace) {
    return { namespace: f.declared_namespace, source: "declared" };
  }
  let base;
  let source = "default";
  if (f.remote_url) {
    const name = scope === "owner_repo" ? repoSlugFromRemote(f.remote_url) : repoNameFromRemote(f.remote_url);
    if (name) {
      base = name;
      source = "remote";
    }
  }
  if (!base && f.toplevel_basename) {
    base = f.toplevel_basename;
    source = "toplevel";
  }
  if (!base && f.cwd_basename) {
    base = f.cwd_basename;
    source = "cwd";
  }
  if (!base) {
    return { namespace: "default", source: "default" };
  }
  return { namespace: withAgent(base, f.agent), source };
}
function resolveNamespace(boot, facts, hs) {
  if (hs) {
    return { namespace: hs.namespace, source: `server:${hs.namespace_source}`, degraded: false };
  }
  if (boot.namespaceEnv) {
    return { namespace: boot.namespaceEnv, source: "env", degraded: true };
  }
  const { namespace, source } = deriveLocalNamespace(facts);
  const prefix = boot.namespacePrefixEnv;
  if (prefix && (source === "remote" || source === "toplevel" || source === "cwd")) {
    return { namespace: `${prefix}/${namespace}`, source: `local-${source}`, degraded: true };
  }
  return { namespace, source: `local-${source}`, degraded: true };
}

// src/handshake.ts
import fs3 from "node:fs";
import path4 from "node:path";
var HANDSHAKE_TTL_MS = 10 * 60 * 1e3;
async function performHandshake(boot, facts, opts = {}) {
  assertBearerTransportSafe(boot.baseUrl, boot.apiKey, {
    MEMINI_REQUIRE_HTTPS: boot.requireHttps ? "1" : "0"
  });
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), opts.timeoutMs ?? 2500);
  try {
    const headers = { "Content-Type": "application/json" };
    if (boot.apiKey) headers["Authorization"] = `Bearer ${boot.apiKey}`;
    if (boot.homeEnv) headers["X-Memini-Home"] = boot.homeEnv;
    const body = JSON.stringify({
      project: facts,
      client: { name: opts.clientName, version: opts.clientVersion }
    });
    const res = await fetch(`${boot.baseUrl}/v1/handshake`, {
      method: "POST",
      headers,
      body,
      signal: controller.signal
    });
    if (!res.ok) return void 0;
    return await res.json();
  } catch {
    return void 0;
  } finally {
    clearTimeout(timer);
  }
}
function handshakeCachePath(ppid, env = process.env) {
  return path4.join(cacheDir(env), "sessions", `pid-${ppid}.handshake.json`);
}
function readCachedHandshake(ppid, cwd, facts, env = process.env, now = Date.now()) {
  try {
    const raw = fs3.readFileSync(handshakeCachePath(ppid, env), "utf8");
    const rec = JSON.parse(raw);
    if (!rec || typeof rec !== "object") return void 0;
    if (typeof rec.writtenAt !== "number" || !Number.isFinite(rec.writtenAt)) return void 0;
    const age = now - rec.writtenAt;
    if (age < 0 || age > HANDSHAKE_TTL_MS) return void 0;
    if (typeof rec.cwd !== "string" || path4.resolve(rec.cwd) !== path4.resolve(cwd)) return void 0;
    if (typeof rec.factsHash !== "string" || rec.factsHash !== factsFingerprint(facts)) return void 0;
    if (!rec.result || typeof rec.result !== "object") return void 0;
    return rec.result;
  } catch {
    return void 0;
  }
}
function writeCachedHandshake(ppid, cwd, facts, result, env = process.env, now = Date.now()) {
  try {
    const p = handshakeCachePath(ppid, env);
    fs3.mkdirSync(path4.dirname(p), { recursive: true });
    const rec = {
      result,
      cwd: path4.resolve(cwd),
      factsHash: factsFingerprint(facts),
      writtenAt: now
    };
    const tmp = `${p}.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`;
    try {
      fs3.writeFileSync(tmp, JSON.stringify(rec));
      fs3.renameSync(tmp, p);
    } catch (e) {
      try {
        fs3.unlinkSync(tmp);
      } catch {
      }
      throw e;
    }
  } catch {
  }
}
function deleteCachedHandshake(ppid, env = process.env) {
  try {
    fs3.rmSync(handshakeCachePath(ppid, env), { force: true });
  } catch {
  }
}
function invalidateAllHandshakes(env = process.env) {
  const dir = path4.join(cacheDir(env), "sessions");
  let names;
  try {
    names = fs3.readdirSync(dir);
  } catch {
    return;
  }
  for (const name of names) {
    if (!name.endsWith(".handshake.json")) continue;
    try {
      fs3.rmSync(path4.join(dir, name), { force: true });
    } catch {
    }
  }
}

// src/enforce/identity.ts
import crypto2 from "node:crypto";
function isContentHash(s) {
  return typeof s === "string" && /^[0-9a-f]{16}$/.test(s);
}
function injectedIdentity(m) {
  const ch = m?.content_hash ?? m?.memory?.content_hash;
  if (isContentHash(ch)) return ch;
  const text = m?.content || m?.summary || "";
  return crypto2.createHash("sha256").update(text).digest("hex").slice(0, 16);
}
function pretoolFingerprint(file, hits) {
  const fingerprintInput = JSON.stringify({
    file,
    items: hits.map((h) => ({ id: h.memory?.id || null, h: injectedIdentity(h) }))
  });
  return crypto2.createHash("sha256").update(fingerprintInput).digest("hex");
}
function briefingContentHash(briefing) {
  return crypto2.createHash("sha256").update(JSON.stringify(briefing)).digest("hex").slice(0, 16);
}

// src/enforce/seen.ts
var MAX_INJECTED_IDS = 512;
function normInjectedEntry(e, fallbackAt) {
  if (!e || typeof e !== "object" || Array.isArray(e) || typeof e.h !== "string") return null;
  return {
    h: e.h,
    at: Number.isFinite(e.at) ? e.at : fallbackAt,
    n: Number.isFinite(e.n) ? e.n : 0
  };
}
function normalizeInjectedState(raw, now = Date.now()) {
  const empty = { n: 0, ids: {} };
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return empty;
  const ids = {};
  if (raw.v === 2) {
    const rawIds = raw.ids && typeof raw.ids === "object" && !Array.isArray(raw.ids) ? raw.ids : {};
    for (const [id, e] of Object.entries(rawIds)) {
      const norm = normInjectedEntry(e, now);
      if (id && norm) ids[id] = norm;
    }
    return { n: Number.isFinite(raw.n) ? raw.n : 0, ids };
  }
  for (const [id, h] of Object.entries(raw)) {
    if (id && typeof h === "string") ids[id] = { h, at: now, n: 0 };
  }
  return { n: 0, ids };
}
function recordInjected(state, id, h, now = Date.now()) {
  if (!state.ids) state.ids = {};
  state.ids[id] = { h, at: now, n: Number.isFinite(state.n) ? state.n : 0 };
  return state;
}
function mergeInjectedStates(disk, mem, now = Date.now()) {
  const m = mem && typeof mem === "object" ? mem : {};
  const memIds = m.ids && typeof m.ids === "object" ? m.ids : {};
  const memN = Number.isFinite(m.n) ? m.n : 0;
  const merged = { ...disk.ids };
  for (const [id, e] of Object.entries(memIds)) {
    const norm = normInjectedEntry(e, now);
    if (!id || !norm) continue;
    const prev = merged[id];
    if (!prev || norm.at >= prev.at) merged[id] = norm;
  }
  const n = Math.max(memN, disk.n);
  let entries = Object.entries(merged);
  if (entries.length > MAX_INJECTED_IDS) {
    entries.sort((a, b) => (b[1]?.at || 0) - (a[1]?.at || 0));
    entries = entries.slice(0, MAX_INJECTED_IDS);
  }
  return { v: 2, n, ids: Object.fromEntries(entries) };
}
function injectedSuppressed(entry, identity, { now, counter, cooldownMs, cooldownPrompts }) {
  if (!entry || typeof entry !== "object") return false;
  if (entry.h === "") return true;
  if (identity && entry.h !== identity) return false;
  if (cooldownMs === 0 && cooldownPrompts === 0) return true;
  const promptDim = cooldownPrompts > 0 && counter > 0 && counter - entry.n < cooldownPrompts;
  const timeDim = cooldownMs > 0 && now - entry.at < cooldownMs;
  return promptDim || timeDim;
}
function cooldownIds(state, { now, cooldownMs, cooldownPrompts }) {
  const ids = state && state.ids && typeof state.ids === "object" ? state.ids : {};
  const counter = Number.isFinite(state?.n) ? state.n : 0;
  const out = [];
  for (const [id, entry] of Object.entries(ids)) {
    if (injectedSuppressed(entry, null, { now, counter, cooldownMs, cooldownPrompts })) out.push(id);
  }
  return out;
}

// src/enforce/budget.ts
function approxTokens(text) {
  if (!text) return 0;
  const words = String(text).trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.ceil(words * 4 / 3));
}
function fitByTokens(items, maxTokens) {
  if (!Array.isArray(items) || items.length === 0) return { items: [], tokens: 0, dropped: 0 };
  if (!Number.isFinite(maxTokens) || maxTokens <= 0) {
    const tokens = items.reduce((sum, s) => sum + approxTokens(s), 0);
    return { items: items.slice(), tokens, dropped: 0 };
  }
  const out = [];
  let used = 0;
  let dropped = 0;
  for (const s of items) {
    const t = approxTokens(s);
    if (used + t > maxTokens) {
      const charBudget = (maxTokens - used) * 4;
      if (charBudget > 20) {
        let cut = s.slice(0, charBudget);
        const lastNL = cut.lastIndexOf("\n");
        if (lastNL > 20) cut = cut.slice(0, lastNL);
        if (cut.length > 20) {
          out.push(cut + "\n[...truncated]");
          used += approxTokens(cut);
          continue;
        }
      }
      dropped++;
      continue;
    }
    out.push(s);
    used += t;
  }
  return { items: out, tokens: used, dropped };
}

// src/enforce/render.ts
var RECALL_DETAIL_HEADER = "<!-- summaries; full text: memory_get with the id from [m:\u2026] -->";
function escapeMeminiTags(content) {
  if (typeof content !== "string") return content;
  return content.replace(/<(\/?)memini/gi, "&lt;$1memini");
}
function truncate(value, max) {
  if (typeof value === "string") {
    return value.length > max ? value.slice(0, max) + "\n[...truncated]" : value;
  }
  if (value && typeof value === "object") {
    let str;
    try {
      str = JSON.stringify(value);
    } catch {
      return value;
    }
    return str.length > max ? str.slice(0, max) + "...[truncated]" : str;
  }
  return value;
}
function memoryHandle(id) {
  return typeof id === "string" && id ? `[m:${id.slice(0, 8)}]` : "";
}
function formatRecallHit(h, labels) {
  const text = escapeMeminiTags(h?.content || h?.summary || "");
  if (!text) return null;
  const h8 = memoryHandle(h?.memory?.id);
  const handle = h8 ? ` ${h8}` : "";
  if (labels.size === 0) {
    return `- (${h.score.toFixed(2)}) ${truncate(text, 240)}${handle}`;
  }
  const tagParts = [];
  if (labels.has("tier") && h.tier) tagParts.push(h.tier);
  if (labels.has("confidence") && typeof h.memory?.confidence === "number") {
    tagParts.push(`conf=${h.memory.confidence.toFixed(2)}`);
  }
  if (labels.has("reason")) tagParts.push("relevant memory");
  const prefix = tagParts.length ? `[${tagParts.join(" \xB7 ")}] ` : "";
  return `- (${h.score.toFixed(2)}) ${prefix}${truncate(text, 240)}${handle}`;
}
function recallHitTruncated(h) {
  if (h?.content_truncated === true || h?.memory?.content_truncated === true) return true;
  const text = escapeMeminiTags(h?.content || h?.summary || "");
  return typeof text === "string" && text.length > 240;
}
function recallDropFooter(dropped) {
  return `[+${dropped} more \u2014 memory_recall for detail]`;
}
function briefingDropFooter(dropped) {
  return `[... ${dropped} item(s) truncated by token budget]`;
}

// src/enforce/telemetry.ts
var SUPPRESSED_KEYS = ["seen", "cooldown", "budget", "unchanged", "score"];
function injectedReport({
  surface,
  sessionId,
  ids,
  tokens,
  chars,
  suppressed
} = {}) {
  const body = {
    session_id: sessionId || "",
    surface,
    source: "claude-code",
    injected_ids: Array.isArray(ids) ? ids.filter((id) => typeof id === "string" && id) : []
  };
  if (Number.isFinite(tokens) && tokens > 0) body.injected_tokens_est = tokens;
  if (Number.isFinite(chars) && chars > 0) body.injected_chars = chars;
  const sup = {};
  for (const k of SUPPRESSED_KEYS) {
    const v = suppressed?.[k];
    if (Number.isFinite(v) && v > 0) sup[k] = v;
  }
  if (Object.keys(sup).length > 0) body.suppressed = sup;
  return body;
}
export {
  BEHAVIOR_KNOBS,
  DEFAULT_TIMEOUT_MS,
  HANDSHAKE_TTL_MS,
  MAX_INJECTED_IDS,
  MAX_NAMESPACE_BYTES,
  MIN_TIMEOUT_MS,
  OVERRIDES_VERSION,
  RECALL_DETAIL_HEADER,
  SESSION_CWD_TTL_MS,
  TRUNCATION_MARKER,
  approxTokens,
  assertBearerTransportSafe,
  briefingContentHash,
  briefingDropFooter,
  buildTurnCapture,
  cacheDir,
  cooldownIds,
  defaultOverridesPath,
  deleteCachedHandshake,
  deleteSessionCwd,
  deriveLocalNamespace,
  effectiveSetting,
  envEnabled,
  envTimeoutMs,
  escapeMeminiTags,
  factsFingerprint,
  fitByTokens,
  formatRecallHit,
  gatherFacts,
  handshakeCachePath,
  injectedIdentity,
  injectedReport,
  injectedSuppressed,
  invalidateAllHandshakes,
  isContentHash,
  isPlaintextBearerUnsafe,
  isSensitive,
  looksLikePluginRoot,
  memoryHandle,
  mergeInjectedStates,
  normInjectedEntry,
  normalizeInjectedState,
  normalizeNamespace,
  overrideKey,
  performHandshake,
  pretoolFingerprint,
  processCwd,
  readBootstrap,
  readCachedHandshake,
  readOverride,
  readOverrides,
  readSessionCwd,
  recallDropFooter,
  recallHitTruncated,
  recordInjected,
  redactByName,
  redactValue,
  repoNameFromRemote,
  repoSlugFromRemote,
  resolveHarnessCwd,
  resolveNamespace,
  sessionCwdPath,
  truncate,
  truncateForCapture,
  validateNamespace,
  writeCachedHandshake,
  writeSessionCwd
};
