// Code generated by packages/memini-client. DO NOT EDIT.
//
// Regenerate with:  mise run build-client
// CI fails on drift via:  mise run client-check
//
// Source of truth: packages/memini-client/src/*.ts
// This file is committed because the plugin ships as raw files with no
// install-time build step — the hooks run under a bare `node`.

// src/redact.ts
var SENSITIVE = /(^|_)(KEY|TOKEN|SECRET|PASSWORD|PASS|BEARER|DSN|CREDENTIALS?)$/i;
function isSensitive(name) {
  return SENSITIVE.test(name);
}
function redactValue(value) {
  if (!value) return "";
  if (value.length <= 12) return "***";
  return `${value.slice(0, 3)}\u2026${value.slice(-4)}`;
}
function redactByName(name, value) {
  return isSensitive(name) ? redactValue(value) : value;
}

// src/namespace-validate.ts
var MAX_NAMESPACE_BYTES = 256;
function normalizeNamespace(ns) {
  let out = String(ns ?? "").trim();
  out = out.replace(/^\/+|\/+$/g, "");
  while (out.includes("//")) out = out.replace(/\/\/+/g, "/");
  return out;
}
function validateNamespace(ns) {
  if (!ns) return "namespace is empty";
  if (Buffer.byteLength(ns, "utf8") > MAX_NAMESPACE_BYTES) {
    return `namespace exceeds ${MAX_NAMESPACE_BYTES} bytes`;
  }
  if (/[\r\n]/.test(ns)) return "namespace contains a newline";
  if (/[\x00-\x1F\x7F]/.test(ns)) return "namespace contains a control character";
  if (/[^\x20-\x7E]/.test(ns)) return "namespace contains a non-ASCII character";
  return null;
}

// src/capture.ts
var TRUNCATION_MARKER = "\n[...truncated]";
function truncateForCapture(s, max) {
  if (typeof max !== "number" || !Number.isFinite(max) || max <= 0) return s;
  const cap = Math.floor(max);
  if (s.length <= cap) return s;
  let i = 0;
  for (let n = 0; i < s.length && n < cap; n++) {
    i += s.codePointAt(i) > 65535 ? 2 : 1;
  }
  if (i >= s.length) return s;
  return s.slice(0, i) + TRUNCATION_MARKER;
}
function buildTurnCapture(userText, assistantText, userMax, assistantMax) {
  return `${truncateForCapture(userText, userMax)}

${truncateForCapture(assistantText, assistantMax)}`;
}

// src/override.ts
import { execSync } from "node:child_process";
import { homedir } from "node:os";
import fs from "node:fs";
import path from "node:path";
var OVERRIDES_VERSION = 1;
var EMPTY = { version: OVERRIDES_VERSION, overrides: {} };
function defaultOverridesPath(env = process.env) {
  const xdg = env["XDG_CONFIG_HOME"];
  const base = xdg && xdg.trim() ? xdg : path.join(homedir(), ".config");
  return path.join(base, "memini", "overrides.json");
}
function overrideKey(cwd) {
  const dir = cwd && cwd.trim() ? cwd : process.cwd();
  try {
    const top = execSync("git rev-parse --show-toplevel", {
      cwd: dir,
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 500
    }).toString().trim();
    if (top) return path.resolve(top);
  } catch {
  }
  return path.resolve(dir);
}
function readOverrides(opts = {}) {
  const p = opts.overridesPath || defaultOverridesPath(opts.env);
  try {
    const parsed = JSON.parse(fs.readFileSync(p, "utf8"));
    if (!parsed || typeof parsed !== "object" || typeof parsed.overrides !== "object") {
      return { ...EMPTY, overrides: {} };
    }
    return {
      version: typeof parsed.version === "number" ? parsed.version : OVERRIDES_VERSION,
      overrides: parsed.overrides || {}
    };
  } catch {
    return { ...EMPTY, overrides: {} };
  }
}
function readOverride(cwd, opts = {}) {
  const file = readOverrides(opts);
  const keys = Object.keys(file.overrides);
  if (keys.length === 0) return void 0;
  const entry = file.overrides[overrideKey(cwd)];
  if (!entry || typeof entry.namespace !== "string" || !entry.namespace.trim()) return void 0;
  return entry;
}

// src/session.ts
import { execFileSync } from "node:child_process";
import { homedir as homedir2, tmpdir } from "node:os";
import fs2 from "node:fs";
import path2 from "node:path";
function cacheDir(env = process.env) {
  const base = env["XDG_CACHE_HOME"] || path2.join(homedir2() || tmpdir(), ".cache");
  return path2.join(base, "memini");
}
function sessionCwdPath(ppid, env = process.env) {
  return path2.join(cacheDir(env), "sessions", `pid-${ppid}.cwd`);
}
var SESSION_CWD_TTL_MS = 6 * 60 * 60 * 1e3;
function writeSessionCwd(ppid, cwd, env = process.env, now = Date.now()) {
  if (!ppid || !cwd || !cwd.trim()) return;
  try {
    const p = sessionCwdPath(ppid, env);
    fs2.mkdirSync(path2.dirname(p), { recursive: true });
    const rec = { cwd: path2.resolve(cwd), writtenAt: now };
    fs2.writeFileSync(p, JSON.stringify(rec));
  } catch {
  }
}
function readSessionCwd(ppid, env = process.env, now = Date.now()) {
  try {
    const raw = fs2.readFileSync(sessionCwdPath(ppid, env), "utf8").trim();
    if (!raw) return void 0;
    const rec = JSON.parse(raw);
    if (!rec || typeof rec.cwd !== "string" || !rec.cwd) return void 0;
    if (typeof rec.writtenAt !== "number" || !Number.isFinite(rec.writtenAt)) return void 0;
    const age = now - rec.writtenAt;
    if (age < 0 || age > SESSION_CWD_TTL_MS) return void 0;
    return fs2.existsSync(rec.cwd) ? rec.cwd : void 0;
  } catch {
    return void 0;
  }
}
function deleteSessionCwd(ppid, env = process.env) {
  if (!ppid) return;
  try {
    fs2.rmSync(sessionCwdPath(ppid, env), { force: true });
  } catch {
  }
}
function processCwd(pid) {
  if (!pid || pid <= 1) return void 0;
  try {
    const link = fs2.readlinkSync(`/proc/${pid}/cwd`);
    if (link && fs2.existsSync(link)) return link;
  } catch {
  }
  if (process.platform === "darwin") {
    try {
      const out = execFileSync("lsof", ["-a", "-d", "cwd", "-p", String(pid), "-Fn"], {
        stdio: ["ignore", "pipe", "ignore"],
        timeout: 1e3
      }).toString();
      for (const line of out.split("\n")) {
        if (line.startsWith("n/")) {
          const p = line.slice(1).trim();
          if (p && fs2.existsSync(p)) return p;
        }
      }
    } catch {
    }
  }
  return void 0;
}
function looksLikePluginRoot(dir, env = process.env) {
  if (!dir) return true;
  const d = path2.resolve(dir);
  const pluginRoot = env["CLAUDE_PLUGIN_ROOT"];
  if (pluginRoot && path2.resolve(pluginRoot) === d) return true;
  return /[/\\](plugins?)[/\\]cache[/\\]/.test(d);
}
function resolveHarnessCwd(env = process.env, ppid = process.ppid) {
  const explicit = env["CLAUDE_PROJECT_DIR"];
  if (explicit && explicit.trim() && !looksLikePluginRoot(explicit, env)) {
    return { cwd: path2.resolve(explicit.trim()), source: "CLAUDE_PROJECT_DIR" };
  }
  const parent = processCwd(ppid);
  if (parent && !looksLikePluginRoot(parent, env)) {
    return { cwd: parent, source: "parent-process" };
  }
  const recorded = readSessionCwd(ppid, env);
  if (recorded && !looksLikePluginRoot(recorded, env)) {
    return { cwd: recorded, source: "session-file" };
  }
  return void 0;
}

// src/bootstrap.ts
var DEFAULT_TIMEOUT_MS = 3e4;
var MIN_TIMEOUT_MS = 100;
var LOOPBACK_HOSTS = /* @__PURE__ */ new Set(["localhost", "127.0.0.1", "::1"]);
function envTimeoutMs(raw, fallback = DEFAULT_TIMEOUT_MS) {
  if (raw == null || raw.trim() === "") return fallback;
  const n = Number(raw.trim());
  if (!Number.isFinite(n)) return fallback;
  return Math.max(MIN_TIMEOUT_MS, Math.trunc(n));
}
function envEnabled(raw, defaultOn) {
  if (raw == null || raw === "") return defaultOn;
  return !/^(0|false|no|off)$/i.test(raw.trim());
}
function readBootstrap(env = process.env) {
  return {
    baseUrl: env["MEMINI_BASE_URL"] || "http://localhost:8080",
    apiKey: env["MEMINI_API_KEY"] || "",
    requireHttps: envEnabled(env["MEMINI_REQUIRE_HTTPS"], false),
    debug: envEnabled(env["MEMINI_DEBUG"], false),
    agent: env["MEMINI_AGENT"] || "",
    namespaceEnv: (env["MEMINI_NAMESPACE"] || "").trim(),
    namespacePrefixEnv: (env["MEMINI_NAMESPACE_PREFIX"] || "").trim(),
    homeEnv: (env["MEMINI_HOME"] || "").trim(),
    timeoutMs: envTimeoutMs(env["MEMINI_TIMEOUT_MS"])
  };
}
function isPlaintextBearerUnsafe(baseUrl, secret) {
  if (!secret) return false;
  try {
    const u = new URL(baseUrl);
    return u.protocol === "http:" && !LOOPBACK_HOSTS.has(u.hostname.replace(/^\[|\]$/g, "").toLowerCase());
  } catch {
    return false;
  }
}
function assertBearerTransportSafe(baseUrl, secret, env = process.env) {
  if (!isPlaintextBearerUnsafe(baseUrl, secret)) return;
  if (!envEnabled(env["MEMINI_REQUIRE_HTTPS"], false)) return;
  throw new Error(
    `memini: a bearer token is configured for plaintext HTTP to ${baseUrl}. The token and memory payloads can be observed on the network; use HTTPS or an SSH tunnel.`
  );
}

// src/settings.ts
var BEHAVIOR_KNOBS = [
  { envName: "MEMINI_CAPTURE_TURNS", wireKey: "capture_turns", kind: "bool", default: true },
  { envName: "MEMINI_SESSION_DIGEST", wireKey: "session_digest", kind: "bool", default: true },
  { envName: "MEMINI_INLINE_EXTRACT", wireKey: "inline_extract", kind: "bool", default: true },
  { envName: "MEMINI_AUTO_SAVE", wireKey: "auto_save", kind: "bool", default: true },
  { envName: "MEMINI_AUTO_SAVE_INTERVAL", wireKey: "auto_save_interval", kind: "int", default: 10 },
  { envName: "MEMINI_AUTO_SAVE_MIN_EVENTS", wireKey: "auto_save_min_events", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_BRIEFING_PINNED", wireKey: "inject_briefing_pinned", kind: "int", default: 5 },
  { envName: "MEMINI_INJECT_BRIEFING_FACTS", wireKey: "inject_briefing_facts", kind: "int", default: 5 },
  { envName: "MEMINI_INJECT_BRIEFING_PROCEDURES", wireKey: "inject_briefing_procedures", kind: "int", default: 5 },
  { envName: "MEMINI_INJECT_BRIEFING_RECENT", wireKey: "inject_briefing_recent", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_BRIEFING_MAX_TOK", wireKey: "inject_briefing_max_tok", kind: "int", default: 0 },
  { envName: "MEMINI_INJECT_PRETOOL_ITEMS", wireKey: "inject_pretool_items", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_PRETOOL_MAX_TOK", wireKey: "inject_pretool_max_tok", kind: "int", default: 0 },
  { envName: "MEMINI_INJECT_PRETOOL_MIN_SCORE", wireKey: "inject_pretool_min_score", kind: "float", default: 0 },
  {
    envName: "MEMINI_INJECT_PRETOOL_TOOLS",
    wireKey: "inject_pretool_tools",
    kind: "list",
    default: ["Read", "Write", "Edit", "MultiEdit", "Glob", "Grep"]
  },
  { envName: "MEMINI_INJECT_DEDUPE", wireKey: "inject_dedupe", kind: "bool", default: true },
  { envName: "MEMINI_INJECT_LABELS", wireKey: "inject_labels", kind: "list", default: [] },
  { envName: "MEMINI_RECALL", wireKey: "recall", kind: "bool", default: true },
  { envName: "MEMINI_CAPTURE", wireKey: "capture", kind: "bool", default: true },
  { envName: "MEMINI_RECALL_LIMIT", wireKey: "recall_limit", kind: "int", default: 3 },
  { envName: "MEMINI_INJECT_RECALL_MAX_TOK", wireKey: "inject_recall_max_tok", kind: "int", default: 0 },
  { envName: "MEMINI_INJECT_RECALL_MIN_SCORE", wireKey: "inject_recall_min_score", kind: "float", default: 0 },
  { envName: "MEMINI_MIN_CAPTURE_CHARS", wireKey: "min_capture_chars", kind: "int", default: 0 },
  { envName: "MEMINI_CAPTURE_USER_MAX_CHARS", wireKey: "capture_user_max_chars", kind: "int", default: 1e3 },
  {
    envName: "MEMINI_CAPTURE_ASSISTANT_MAX_CHARS",
    wireKey: "capture_assistant_max_chars",
    kind: "int",
    default: 3e3
  },
  // Also read at the transport layer (bootstrap.ts's timeoutMs), because a
  // request timeout has to exist before the handshake that fetches settings.
  // Both spellings share DEFAULT_TIMEOUT_MS/MIN_TIMEOUT_MS, so there is exactly
  // one number: raising it here (server-side) or in the env both work.
  {
    envName: "MEMINI_TIMEOUT_MS",
    wireKey: "request_timeout_ms",
    kind: "int",
    default: DEFAULT_TIMEOUT_MS,
    min: MIN_TIMEOUT_MS
  }
];
function parseIntKnob(raw, fallback, min = 0) {
  const n = Number.parseInt(raw, 10);
  if (!Number.isFinite(n) || n < 0) return fallback;
  return Math.max(min, n);
}
function parseFloatKnob(raw, fallback) {
  const n = Number.parseFloat(raw);
  return Number.isFinite(n) && n >= 0 ? n : fallback;
}
function parseListKnob(raw) {
  return raw.split(/[|,]/).map((s) => s.trim().toLowerCase()).filter(Boolean);
}
function effectiveSetting(knob, server, env = process.env) {
  const raw = env[knob.envName];
  if (raw != null && raw !== "") {
    let value;
    switch (knob.kind) {
      case "bool":
        value = !/^(0|false|no|off)$/i.test(raw.trim());
        break;
      case "int":
        value = parseIntKnob(raw, knob.default, knob.min);
        break;
      case "float":
        value = parseFloatKnob(raw, knob.default);
        break;
      case "list":
        value = parseListKnob(raw);
        break;
    }
    return { value, source: "env-override" };
  }
  if (server && Object.prototype.hasOwnProperty.call(server, knob.wireKey)) {
    return { value: server[knob.wireKey], source: "server" };
  }
  return { value: knob.default, source: "default" };
}

// src/facts.ts
import { execFileSync as execFileSync2 } from "node:child_process";
import path3 from "node:path";
import crypto from "node:crypto";
function gitOut(args, dir) {
  try {
    const out = execFileSync2("git", args, {
      cwd: dir,
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 500
    }).toString().trim();
    return out || void 0;
  } catch {
    return void 0;
  }
}
function gatherFacts(cwd, env = process.env) {
  const dir = cwd && cwd.trim() ? cwd : process.cwd();
  const facts = {
    cwd_basename: path3.basename(dir)
  };
  const remote = gitOut(["remote", "get-url", "origin"], dir);
  if (remote) facts.remote_url = remote;
  const toplevel = gitOut(["rev-parse", "--show-toplevel"], dir);
  if (toplevel) {
    facts.toplevel_path = toplevel;
    facts.toplevel_basename = path3.basename(toplevel);
  }
  const agent = env["MEMINI_AGENT"];
  if (agent) facts.agent = agent;
  const ns = (env["MEMINI_NAMESPACE"] || "").trim();
  if (ns) facts.env_namespace = ns;
  const prefix = (env["MEMINI_NAMESPACE_PREFIX"] || "").trim();
  if (prefix) facts.env_namespace_prefix = prefix;
  return facts;
}
function factsFingerprint(f) {
  const rec = f;
  const keys = Object.keys(f).filter((k) => rec[k] !== void 0).sort();
  const parts = keys.map((k) => `${k}=${rec[k]}`);
  return crypto.createHash("sha256").update(parts.join("\n"), "utf8").digest("hex").slice(0, 16);
}

// src/resolve.ts
function remotePathSegments(url) {
  if (typeof url !== "string" || !url) return [];
  const cleaned = url.trim().replace(/\/+$/, "").replace(/\.git$/i, "");
  if (!cleaned) return [];
  const scpMatch = cleaned.match(/^[^/:]+:[^/]/);
  const p = scpMatch ? cleaned.slice(scpMatch[0].indexOf(":") + 1) : cleaned;
  return p.split("/").filter(Boolean);
}
function repoNameFromRemote(url) {
  const segs = remotePathSegments(url);
  return segs.length ? segs[segs.length - 1] : void 0;
}
function repoSlugFromRemote(url) {
  const segs = remotePathSegments(url);
  if (!segs.length) return void 0;
  if (segs.length === 1) return segs[0];
  const owner = segs[segs.length - 2].replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
  const repo = segs[segs.length - 1];
  return owner ? `${owner}-${repo}` : repo;
}
function withAgent(ns, agent) {
  const trimmed = (agent || "").trim();
  if (!trimmed) return ns;
  const seg = trimmed.replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
  return seg ? `${ns}/${seg}` : ns;
}
function deriveLocalNamespace(f, scope = "repo") {
  if (f.declared_namespace) {
    return { namespace: f.declared_namespace, source: "declared" };
  }
  let base;
  let source = "default";
  if (f.remote_url) {
    const name = scope === "owner_repo" ? repoSlugFromRemote(f.remote_url) : repoNameFromRemote(f.remote_url);
    if (name) {
      base = name;
      source = "remote";
    }
  }
  if (!base && f.toplevel_basename) {
    base = f.toplevel_basename;
    source = "toplevel";
  }
  if (!base && f.cwd_basename) {
    base = f.cwd_basename;
    source = "cwd";
  }
  if (!base) {
    return { namespace: "default", source: "default" };
  }
  return { namespace: withAgent(base, f.agent), source };
}
function resolveNamespace(boot, facts, hs) {
  if (hs) {
    return { namespace: hs.namespace, source: `server:${hs.namespace_source}`, degraded: false };
  }
  if (boot.namespaceEnv) {
    return { namespace: boot.namespaceEnv, source: "env", degraded: true };
  }
  const { namespace, source } = deriveLocalNamespace(facts);
  const prefix = boot.namespacePrefixEnv;
  if (prefix && (source === "remote" || source === "toplevel" || source === "cwd")) {
    return { namespace: `${prefix}/${namespace}`, source: `local-${source}`, degraded: true };
  }
  return { namespace, source: `local-${source}`, degraded: true };
}

// src/handshake.ts
import fs3 from "node:fs";
import path4 from "node:path";
var HANDSHAKE_TTL_MS = 10 * 60 * 1e3;
async function performHandshake(boot, facts, opts = {}) {
  assertBearerTransportSafe(boot.baseUrl, boot.apiKey, {
    MEMINI_REQUIRE_HTTPS: boot.requireHttps ? "1" : "0"
  });
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), opts.timeoutMs ?? 2500);
  try {
    const headers = { "Content-Type": "application/json" };
    if (boot.apiKey) headers["Authorization"] = `Bearer ${boot.apiKey}`;
    if (boot.homeEnv) headers["X-Memini-Home"] = boot.homeEnv;
    const body = JSON.stringify({
      project: facts,
      client: { name: opts.clientName, version: opts.clientVersion }
    });
    const res = await fetch(`${boot.baseUrl}/v1/handshake`, {
      method: "POST",
      headers,
      body,
      signal: controller.signal
    });
    if (!res.ok) return void 0;
    return await res.json();
  } catch {
    return void 0;
  } finally {
    clearTimeout(timer);
  }
}
function handshakeCachePath(ppid, env = process.env) {
  return path4.join(cacheDir(env), "sessions", `pid-${ppid}.handshake.json`);
}
function readCachedHandshake(ppid, cwd, facts, env = process.env, now = Date.now()) {
  try {
    const raw = fs3.readFileSync(handshakeCachePath(ppid, env), "utf8");
    const rec = JSON.parse(raw);
    if (!rec || typeof rec !== "object") return void 0;
    if (typeof rec.writtenAt !== "number" || !Number.isFinite(rec.writtenAt)) return void 0;
    const age = now - rec.writtenAt;
    if (age < 0 || age > HANDSHAKE_TTL_MS) return void 0;
    if (typeof rec.cwd !== "string" || path4.resolve(rec.cwd) !== path4.resolve(cwd)) return void 0;
    if (typeof rec.factsHash !== "string" || rec.factsHash !== factsFingerprint(facts)) return void 0;
    if (!rec.result || typeof rec.result !== "object") return void 0;
    return rec.result;
  } catch {
    return void 0;
  }
}
function writeCachedHandshake(ppid, cwd, facts, result, env = process.env, now = Date.now()) {
  try {
    const p = handshakeCachePath(ppid, env);
    fs3.mkdirSync(path4.dirname(p), { recursive: true });
    const rec = {
      result,
      cwd: path4.resolve(cwd),
      factsHash: factsFingerprint(facts),
      writtenAt: now
    };
    const tmp = `${p}.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`;
    try {
      fs3.writeFileSync(tmp, JSON.stringify(rec));
      fs3.renameSync(tmp, p);
    } catch (e) {
      try {
        fs3.unlinkSync(tmp);
      } catch {
      }
      throw e;
    }
  } catch {
  }
}
function deleteCachedHandshake(ppid, env = process.env) {
  try {
    fs3.rmSync(handshakeCachePath(ppid, env), { force: true });
  } catch {
  }
}
function invalidateAllHandshakes(env = process.env) {
  const dir = path4.join(cacheDir(env), "sessions");
  let names;
  try {
    names = fs3.readdirSync(dir);
  } catch {
    return;
  }
  for (const name of names) {
    if (!name.endsWith(".handshake.json")) continue;
    try {
      fs3.rmSync(path4.join(dir, name), { force: true });
    } catch {
    }
  }
}
export {
  BEHAVIOR_KNOBS,
  DEFAULT_TIMEOUT_MS,
  HANDSHAKE_TTL_MS,
  MAX_NAMESPACE_BYTES,
  MIN_TIMEOUT_MS,
  OVERRIDES_VERSION,
  SESSION_CWD_TTL_MS,
  TRUNCATION_MARKER,
  assertBearerTransportSafe,
  buildTurnCapture,
  cacheDir,
  defaultOverridesPath,
  deleteCachedHandshake,
  deleteSessionCwd,
  deriveLocalNamespace,
  effectiveSetting,
  envEnabled,
  envTimeoutMs,
  factsFingerprint,
  gatherFacts,
  handshakeCachePath,
  invalidateAllHandshakes,
  isPlaintextBearerUnsafe,
  isSensitive,
  looksLikePluginRoot,
  normalizeNamespace,
  overrideKey,
  performHandshake,
  processCwd,
  readBootstrap,
  readCachedHandshake,
  readOverride,
  readOverrides,
  readSessionCwd,
  redactByName,
  redactValue,
  repoNameFromRemote,
  repoSlugFromRemote,
  resolveHarnessCwd,
  resolveNamespace,
  sessionCwdPath,
  truncateForCapture,
  validateNamespace,
  writeCachedHandshake,
  writeSessionCwd
};
