package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	mcpsdk "github.com/modelcontextprotocol/go-sdk/mcp"

	mcpapi "github.com/eleboucher/memini/internal/api/mcp"
	"github.com/eleboucher/memini/internal/service"
)

// The MCP reference is enumerated from a running server rather than parsed out
// of the source. The tools' input schemas are built at runtime by a generic
// helper (enumSchema[rememberArgs]), so there is no literal in the file for an
// AST walker to read; asking the server what it registered is both simpler and
// impossible to get out of step with what an agent actually sees.
//
// memory_answer is only registered when an LLM is configured, so the server is
// built twice and the difference is what tells us which tools are conditional.
// That fact was documented nowhere, and it matters: without an LLM, agents do
// not see the tool at all.

// noopCompleter stands in for a chat model so that HasAnswerer reports true and
// the conditional tools register. It is never called.
type noopCompleter struct{}

func (noopCompleter) Complete(_ context.Context, _, _ string) (string, error) { return "", nil }

type toolDoc struct {
	Name        string
	Title       string
	Description string
	Schema      *mcpsdk.Tool
	NeedsLLM    bool
	Annotation  string
}

func listTools(ctx context.Context, withLLM bool) ([]*mcpsdk.Tool, string, error) {
	var opts []service.Option
	if withLLM {
		opts = append(opts, service.WithAnswerer(noopCompleter{}))
	}
	svc := service.New(nil, nil, opts...)
	srv := mcpapi.NewServer(svc, "default", "", "")

	st, ct := mcpsdk.NewInMemoryTransports()
	ss, err := srv.Connect(ctx, st, nil)
	if err != nil {
		return nil, "", err
	}
	defer ss.Close() //nolint:errcheck

	cli := mcpsdk.NewClient(&mcpsdk.Implementation{Name: "gendocs", Version: "0"}, nil)
	cs, err := cli.Connect(ctx, ct, nil)
	if err != nil {
		return nil, "", err
	}
	defer cs.Close() //nolint:errcheck

	res, err := cs.ListTools(ctx, nil)
	if err != nil {
		return nil, "", err
	}
	// The instructions are the one server-controlled string that can teach
	// cross-tool policy, since per-tool descriptions are read in isolation
	// during tool selection. Every client receives it on initialize and nothing
	// documented that it existed.
	var instructions string
	if ir := cs.InitializeResult(); ir != nil {
		instructions = ir.Instructions
	}
	return res.Tools, instructions, nil
}

func genMCP(out string) error {
	ctx := context.Background()

	base, _, err := listTools(ctx, false)
	if err != nil {
		return fmt.Errorf("enumerating tools without an LLM: %w", err)
	}
	full, instructions, err := listTools(ctx, true)
	if err != nil {
		return fmt.Errorf("enumerating tools with an LLM: %w", err)
	}

	always := map[string]bool{}
	for _, t := range base {
		always[t.Name] = true
	}

	docs := make([]toolDoc, 0, len(full))
	for _, t := range full {
		d := toolDoc{
			Name:        t.Name,
			Title:       t.Title,
			Description: t.Description,
			Schema:      t,
			NeedsLLM:    !always[t.Name],
		}
		if a := t.Annotations; a != nil {
			switch {
			case a.DestructiveHint != nil && *a.DestructiveHint:
				d.Annotation = "destructive"
			case a.ReadOnlyHint:
				d.Annotation = "read-only"
			default:
				d.Annotation = "additive"
			}
		}
		docs = append(docs, d)
	}
	sort.Slice(docs, func(i, j int) bool { return toolOrder(docs[i].Name) < toolOrder(docs[j].Name) })

	md := renderMCP(docs, instructions)
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	return os.WriteFile(out, []byte(md), 0o644)
}

// toolOrder puts the tools in the order an agent meets them rather than
// alphabetically, which would open the page on memory_answer.
func toolOrder(name string) int {
	order := []string{
		"memory_briefing", "memory_recall", "memory_remember", "memory_answer",
		"memory_list", "memory_get", "memory_history", "memory_update", "memory_forget",
	}
	for i, n := range order {
		if n == name {
			return i
		}
	}
	return len(order)
}

func renderMCP(docs []toolDoc, instructions string) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by cmd/gendocs from internal/api/mcp. DO NOT EDIT. -->\n")
	b.WriteString("<!-- Regenerate with: mise run docs -->\n\n")
	b.WriteString("# MCP tools\n\n")
	b.WriteString("The tools an agent sees when it connects to memini, enumerated from the server itself\n")
	b.WriteString("so this page cannot drift from what is actually registered.\n\n")
	b.WriteString("Two transports expose them, and both register the same tools:\n\n")
	b.WriteString("- **Streamable HTTP**, at `http://<host>:8080/mcp`, for a shared always-on server.\n")
	b.WriteString("- **stdio**, via `memini mcp`, for a server the agent spawns per session.\n\n")
	b.WriteString("See [integrations](../../integrations/) for ready-to-paste client configuration.\n\n")

	b.WriteString("## The tools\n\n")
	b.WriteString("| Tool | Does | Available |\n| --- | --- | --- |\n")
	for _, d := range docs {
		avail := "always"
		if d.NeedsLLM {
			avail = "**only with an LLM configured**"
		}
		fmt.Fprintf(&b, "| [`%s`](#%s) | %s | %s |\n", d.Name, strings.ReplaceAll(d.Name, "_", "_"), d.Title, avail)
	}
	b.WriteString("\n")
	b.WriteString("`memory_answer` is registered only when `MEMINI_LLM_BASE_URL` is set. Without an LLM the\n")
	b.WriteString("tool does not exist, rather than existing and failing, so an agent will not try to call it.\n\n")

	if instructions != "" {
		b.WriteString("## Server instructions\n\n")
		b.WriteString("memini also sends this policy to every client on connect. A tool description is read in\n")
		b.WriteString("isolation while the model is choosing a tool, so it cannot teach cross-tool behaviour like\n")
		b.WriteString("call order or when to write proactively. This is where that lives, and it is worth reading:\n")
		b.WriteString("it is what the agent is told about how to use memini.\n\n")
		b.WriteString("```text\n" + strings.TrimRight(instructions, "\n") + "\n```\n\n")
	}

	for _, d := range docs {
		fmt.Fprintf(&b, "## `%s`\n\n", d.Name)
		meta := d.Annotation
		if d.NeedsLLM {
			meta += ", requires an LLM"
		}
		fmt.Fprintf(&b, "*%s*\n\n", meta)
		b.WriteString(escapeAngles(d.Description) + "\n\n")

		params := schemaParams(d.Schema)
		if len(params) == 0 {
			b.WriteString("No parameters beyond the ones every tool takes.\n\n")
			continue
		}
		b.WriteString("| Parameter | Type | Required | Description |\n| --- | --- | --- | --- |\n")
		for _, p := range params {
			req := ""
			if p.Required {
				req = "yes"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", p.Name, p.Type, req, tableCell(p.Desc))
		}
		b.WriteString("\n")
	}
	return b.String()
}

type param struct {
	Name     string
	Type     string
	Required bool
	Desc     string
}

// propSchema is one property of a tool's input schema. JSON Schema allows
// "type" to be either a string or a list ("type": ["null", "array"] is how the
// optional slice parameters come out), so it is decoded loosely and normalised
// by typeName. Decoding it as a plain string silently fails the whole document,
// which is worth knowing: it made every tool with an explicit schema render as
// taking no parameters at all.
type propSchema struct {
	Type        any         `json:"type"`
	Description string      `json:"description"`
	Enum        []any       `json:"enum"`
	Items       *propSchema `json:"items"`
}

// typeName renders a JSON Schema type as something a reader recognises,
// dropping the "null" that marks an optional field.
func (p *propSchema) typeName() string {
	var names []string
	switch t := p.Type.(type) {
	case string:
		names = []string{t}
	case []any:
		for _, v := range t {
			if s, ok := v.(string); ok && s != "null" {
				names = append(names, s)
			}
		}
	}
	if len(names) == 0 {
		return "any"
	}
	name := strings.Join(names, " or ")
	if name == "array" && p.Items != nil {
		if inner := p.Items.typeName(); inner != "any" {
			return inner + "[]"
		}
	}
	return name
}

// schemaParams flattens a tool's input schema into a table.
func schemaParams(t *mcpsdk.Tool) []param {
	if t == nil || t.InputSchema == nil {
		return nil
	}
	raw, err := json.Marshal(t.InputSchema)
	if err != nil {
		return nil
	}
	var s struct {
		Properties map[string]propSchema `json:"properties"`
		Required   []string              `json:"required"`
	}
	if err := json.Unmarshal(raw, &s); err != nil {
		return nil
	}
	req := map[string]bool{}
	for _, r := range s.Required {
		req[r] = true
	}

	out := make([]param, 0, len(s.Properties))
	for name, p := range s.Properties {
		desc := p.Description
		enums := p.Enum
		if len(enums) == 0 && p.Items != nil {
			enums = p.Items.Enum
		}
		if len(enums) > 0 {
			vals := make([]string, 0, len(enums))
			for _, e := range enums {
				vals = append(vals, fmt.Sprintf("`%v`", e))
			}
			if desc != "" && !strings.HasSuffix(desc, ".") {
				desc += "."
			}
			if desc != "" {
				desc += " "
			}
			desc += "One of " + strings.Join(vals, ", ") + "."
		}
		out = append(out, param{Name: name, Type: p.typeName(), Required: req[name], Desc: desc})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Required != out[j].Required {
			return out[i].Required
		}
		return out[i].Name < out[j].Name
	})
	return out
}
