package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// The REST reference is an index over api/openapi.yaml, which is already the
// source of truth (the server handlers are generated from it, and CI fails if
// they drift). Rendering a browsable list of it costs nothing and closes the
// gap where /v1/fsck and /v1/links were mentioned in no document at all.
//
// This is deliberately an index rather than a full API document. The spec has
// the schemas; a reader who needs a request body should open it, or point a
// Swagger UI at it. What was missing was a way to find out that an endpoint
// exists.

// operation is one method on a path. The value under a path is decoded as a raw
// node first, because a path object can also carry a shared "parameters"
// sequence alongside its methods, and decoding that straight into a struct fails
// the whole document.
type operation struct {
	Summary     string `yaml:"summary"`
	Description string `yaml:"description"`
}

type openAPI struct {
	Paths map[string]map[string]yaml.Node `yaml:"paths"`
}

// httpMethods is the allowlist that separates real operations from a path
// object's other keys.
var httpMethods = map[string]bool{
	"get": true, "post": true, "put": true, "patch": true, "delete": true, "head": true, "options": true,
}

// restGroup buckets the endpoints by what an operator is trying to do, since
// the spec's own ordering is alphabetical and tells you nothing.
type restGroup struct {
	Title  string
	Intro  string
	Prefix []string
}

var restGroups = []restGroup{
	{
		Title:  "Memories",
		Intro:  "The core read and write surface. `POST /v1/search` is the REST equivalent of the `memory_recall` MCP tool.",
		Prefix: []string{"/v1/memories", "/v1/search", "/v1/answer"},
	},
	{
		Title: "Namespaces and scoping",
		Intro: "Inspect and repair how memories are partitioned. See [scopes](../scopes.md) for the model. " +
			"`GET /v1/namespaces/readset` answers \"which namespaces would this call actually search?\", " +
			"which is the fastest way to debug recall that returns too much or too little.",
		Prefix: []string{"/v1/namespaces", "/v1/links"},
	},
	{
		Title: "Configuration handshake",
		Intro: "The client→server config handshake. `POST /v1/handshake` resolves the namespace, " +
			"identity, and behavioral settings from client-supplied project facts; `/v1/self` and " +
			"`/v1/settings/defaults` read and edit the settings layers; `/v1/pins` manages the " +
			"explicit project→namespace pins that beat derivation.",
		Prefix: []string{"/v1/handshake", "/v1/self", "/v1/settings", "/v1/pins"},
	},
	{
		Title:  "Maintenance",
		Intro:  "Run the hygiene passes on demand rather than waiting for the background schedule.",
		Prefix: []string{"/v1/dedup", "/v1/fsck", "/v1/stats", "/v1/activity"},
	},
	{
		Title:  "API keys",
		Intro:  "Requires the admin key (`MEMINI_API_KEY`). See [API keys](../api-keys.md).",
		Prefix: []string{"/v1/keys"},
	},
	{
		Title:  "Operational",
		Intro:  "Unauthenticated except for `/metrics`, which the admin key gates unless `MEMINI_METRICS_ADDR` moves it to its own listener.",
		Prefix: []string{"/healthz", "/readyz", "/metrics"},
	},
}

func genREST(specPath, out string) error {
	b, err := os.ReadFile(specPath)
	if err != nil {
		return err
	}
	var spec openAPI
	if err := yaml.Unmarshal(b, &spec); err != nil {
		return err
	}
	if len(spec.Paths) == 0 {
		return fmt.Errorf("no paths found in %s", specPath)
	}

	type row struct{ method, path, summary string }
	byGroup := map[string][]row{}
	seen := map[string]bool{}

	paths := make([]string, 0, len(spec.Paths))
	for p := range spec.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, p := range paths {
		title := ""
		for _, g := range restGroups {
			for _, pre := range g.Prefix {
				if p == pre || strings.HasPrefix(p, pre+"/") {
					title = g.Title
					break
				}
			}
			if title != "" {
				break
			}
		}
		if title == "" {
			return fmt.Errorf("path %s belongs to no section; add it to restGroups in cmd/gendocs/rest.go", p)
		}
		seen[p] = true

		ops := spec.Paths[p]
		methods := make([]string, 0, len(ops))
		for m := range ops {
			if httpMethods[strings.ToLower(m)] {
				methods = append(methods, m)
			}
		}
		sort.Strings(methods)
		for _, m := range methods {
			node := ops[m]
			var op operation
			if err := node.Decode(&op); err != nil {
				return fmt.Errorf("%s %s: %w", m, p, err)
			}
			s := op.Summary
			if s == "" {
				s = op.Description
			}
			byGroup[title] = append(byGroup[title], row{strings.ToUpper(m), p, s})
		}
	}

	var sb strings.Builder
	sb.WriteString("<!-- Generated by cmd/gendocs from api/openapi.yaml. DO NOT EDIT. -->\n")
	sb.WriteString("<!-- Regenerate with: mise run docs -->\n\n")
	sb.WriteString("# REST API\n\n")
	sb.WriteString("Every endpoint the server exposes, indexed from [`api/openapi.yaml`](../../api/openapi.yaml),\n")
	sb.WriteString("which is the source of truth: the server's handlers are generated from it.\n\n")
	sb.WriteString("This page tells you what exists. For request and response schemas, read the spec, or\n")
	sb.WriteString("point a Swagger or Redoc instance at it.\n\n")
	sb.WriteString("Every route takes the namespace from the `X-Memini-Namespace` header rather than the\n")
	sb.WriteString("path, so a hierarchical name like `acme/phoenix` needs no encoding and survives any\n")
	sb.WriteString("proxy. The caller's personal namespace travels in `X-Memini-Home`.\n\n")

	for _, g := range restGroups {
		rows := byGroup[g.Title]
		if len(rows) == 0 {
			continue
		}
		fmt.Fprintf(&sb, "## %s\n\n", g.Title)
		if g.Intro != "" {
			sb.WriteString(g.Intro + "\n\n")
		}
		sb.WriteString("| Endpoint | Does |\n| --- | --- |\n")
		for _, r := range rows {
			fmt.Fprintf(&sb, "| `%s %s` | %s |\n", r.method, r.path, tableCell(r.summary))
		}
		sb.WriteString("\n")
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	return os.WriteFile(out, []byte(sb.String()), 0o644)
}
