/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (verifies storage backend) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Protected by bearer auth when MEMINI_API_KEY is set; unauthenticated otherwise.
         */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fsck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a consistency sweep (purge expired, enforce short-term cap, audit duplicates) */
        post: operations["runFsck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dedup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Collapse near-duplicate memories (vector cluster) — tombstone the lower-scored members of each cluster
         * @description Clusters live memories by embedding similarity (cosine ≥
         *     `similarity`) and tombstones the lower-RetentionScore members of each
         *     cluster, pointing them at the cluster's representative. The action is
         *     reversible (SupersededBy → representative) and the duplicates remain in
         *     storage but are hidden from default search results. Dry-run reports the
         *     actions without committing them.
         *
         *     Scoped to the request's namespace by default — the common case is
         *     cleaning up right after a large import into one namespace, where
         *     exports are typically full of restatements. Set `all_namespaces: true`
         *     to run the pass over every namespace instead.
         */
        post: operations["runDedup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List memories in a namespace (backs the admin UI browser) */
        get: operations["listMemories"];
        put?: never;
        /** Remember (store) a memory */
        post: operations["rememberMemory"];
        /**
         * Delete every memory in the namespace carrying a tag
         * @description Bulk-deletes all memories in the request's namespace that carry the given tag. Combined with the import provenance tag (import:<source>:<date>), this undoes a single bulk import in one call. The tag query parameter is required to avoid an accidental delete-everything.
         */
        delete: operations["forgetByTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-namespace overview (counts by tier, accesses, importance) */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the distinct namespaces holding memories */
        get: operations["listNamespaces"];
        put?: never;
        post?: never;
        /**
         * Delete every memory in the request namespace
         * @description Deletes all memories in the namespace given by the X-Memini-Namespace header. The namespace comes from the header (not the URL path), so a hierarchical name like "work/memini" needs no path encoding and works through any proxy.
         */
        delete: operations["deleteNamespace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespaces/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layered session-start briefing for the request namespace
         * @description A query-less summary for injecting context when a session opens: the most durable facts and procedures, recent episodic activity, and pinned memories. The namespace comes from the X-Memini-Namespace header. Backs the plugin's SessionStart hook.
         */
        get: operations["getBriefing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespaces/read-set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the structural read-set for the request namespace
         * @description Introspection endpoint: which namespaces a recall/briefing on the request namespace would draw from by default, and why (origin) — independent of any one request's tier filter. Header-scoped like `/v1/namespaces/briefing` (no path param): the namespace comes from X-Memini-Namespace, and X-Memini-Home, when set, contributes the home leg.
         */
        get: operations["getReadSet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/links": {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        /** List outgoing namespace links from the request namespace */
        get: operations["listLinks"];
        put?: never;
        /**
         * Create or replace a namespace link (cross-namespace read edge)
         * @description Adds a durable-tier read link from the request namespace (X-Memini-Namespace header, the src) to another namespace (dst): recall/briefing scoped to src additionally reads dst's durable (semantic/procedural) memories, same as an ancestor namespace. Idempotent — POSTing again with the same dst replaces its tiers/note. dst is normalized and rejected with 400 when empty, invalid, or equal to src (no self-links).
         */
        post: operations["putLink"];
        /** Delete a namespace link */
        delete: operations["deleteLink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespaces/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relocate every memory in the request namespace to another namespace
         * @description Moves all memories (including superseded and expired) from the request namespace (X-Memini-Namespace header) to the target namespace. The target is normalized (surrounding whitespace/slashes trimmed, duplicate separators collapsed) and rejected with 400 when it contains "*" or equals the source. Supports dry-run. Backed by the same Move operation as `memini namespace move`.
         */
        post: operations["moveNamespace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespaces/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split the request namespace by metadata keys
         * @description Regroups the request namespace (X-Memini-Namespace header) by metadata, moving each record to the namespace named by the first of the given keys it carries. Supports dry-run. Backed by the same Split operation as `memini namespace split`.
         */
        post: operations["splitNamespace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}/reassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a single memory to a different namespace
         * @description Relocates one memory to the target namespace. The memory must exist in the request namespace (via the X-Memini-Namespace header); otherwise 404. The target is normalized (surrounding whitespace/slashes trimmed, duplicate separators collapsed) and rejected with 400 when it contains "*" or equals the request namespace. Backed by Store.Reassign.
         */
        post: operations["reassignMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Fetch a memory by ID */
        get: operations["getMemory"];
        put?: never;
        post?: never;
        /** Forget (delete) a memory */
        delete: operations["forgetMemory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}/history": {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * The full version chain (supersession lineage) of a memory
         * @description Returns every version linked to this memory by supersession, oldest first: the memories it superseded and the ones that superseded it, including tombstoned rows. Useful for auditing how a fact evolved.
         */
        get: operations["getMemoryHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}/supersede": {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tombstone a memory, recording it was replaced by `by`.
         * @description Stamps `superseded_by` and `valid_to` on the target. The row stays in the store for audit/time-travel and is hard-deleted by the maintenance sweeper after `TombstoneTTL`.
         */
        post: operations["supersedeMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recall memories via hybrid (vector + keyword) search */
        post: operations["searchMemories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recall memories and answer a question grounded on them (requires an LLM) */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Tier: "working" | "episodic" | "semantic" | "procedural";
        /** @enum {string} */
        Level: "explicit" | "deduced";
        RememberRequest: {
            content: string;
            /** @description Omit to let the server choose: the content is classified by the marker heuristic (a terse, unhedged decision/preference/problem lands in semantic/procedural, stamped metadata.tier_classified=marker), falling back to working. Classification never picks working (the default) — it only raises to semantic/procedural. */
            tier?: components["schemas"]["Tier"];
            summary?: string;
            tags?: string[];
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: double */
            importance?: number;
            /** @description Label the derivation provenance (explicit vs deduced) at write time. Omit to leave unset (default, legacy rows, auto-tagged by service). */
            level?: components["schemas"]["Level"];
            /** @description Overrides the tier default TTL; negative means never expire. */
            ttl_seconds?: number;
            /** @description Upserts an existing memory when provided. */
            id?: string;
            /**
             * Format: date-time
             * @description Start of the interval the fact was true. Defaults to now; backdate it to record a historical fact so time-travel (as_of) recall surfaces it.
             */
            valid_from?: string;
            /**
             * Format: date-time
             * @description End of the interval the fact was true (for recording a fact that was true only in the past). Omit for a fact that is still true.
             */
            valid_to?: string;
            /**
             * Format: double
             * @description Seed corroboration for a durable fact (e.g. a trusted import). Omit to use the default seed; ignored for short-term tiers.
             */
            confidence?: number;
            /** @description Write-side namespace scoping. Omit or "project" (default) writes to the request namespace itself. "personal" writes to the caller's home namespace (X-Memini-Home header / MEMINI_HOME on the client) instead — an error if no home namespace is configured. Any other value must name an ancestor of the request namespace, either its full path or an unambiguous last path segment (e.g. "acme" for request namespace "acme/phoenix/api"), and the write lands there instead. Ignored for non-durable writes: an episodic/working memory always stays in the request namespace regardless of visibility. */
            visibility?: string;
        };
        SupersedeRequest: {
            /** @description ID of the memory that replaces the target. */
            by: string;
        };
        /** @description Optional. Returned on POST /v1/memories when the write's nearest same-tier candidate scored at/above MEMINI_WRITE_DEDUP_SCORE and MEMINI_WRITE_DEDUP_ACTION is "hint". The caller can decide whether to merge into the near-duplicate via memory_update. */
        MergeHint: {
            /** @description ID of the near-duplicate memory. */
            similar_id?: string;
            /** @description Preview (≤200 chars) of the near-duplicate memory's content. */
            similar_content?: string;
            /**
             * Format: double
             * @description Fused similarity between the new write and the near-duplicate (0..1).
             */
            score?: number;
            tier?: components["schemas"]["Tier"];
        };
        SearchRequest: {
            query: string;
            tiers?: components["schemas"]["Tier"][];
            levels?: components["schemas"]["Level"][];
            /** @description A memory must carry every listed tag (AND). */
            tags?: string[];
            /** @description A memory's top-level metadata must contain every listed key=value pair (AND). */
            metadata?: {
                [key: string]: string;
            };
            /** @description Drop memories whose top-level metadata carries any of these key=value pairs (the inverse of metadata). Lets a caller keep its own just-written memories out of recall — e.g. excluding the current session's captured turns so they are not echoed back as memory. */
            exclude_metadata?: {
                [key: string]: string;
            };
            /**
             * @description When true, disable the server-side temporal echo guard for this call: just-captured episodic turn captures (metadata.format="turn" younger than the server's window, default 5m) are NOT dropped. Default (false) drops them — a just-captured turn is live context, not long-term memory, and echoing it back makes the agent parrot itself. Opt in only when you genuinely need fresh turns.
             * @default false
             */
            include_fresh_turns: boolean;
            /**
             * @description When true and an LLM is configured, rewrite the query into 2-3 diverse variants before recall and fuse results via RRF. Cheapest read-path LLM lever; opt-in per call.
             * @default false
             */
            query_rewrite: boolean;
            /** @default 10 */
            limit: number;
            /** @default false */
            include_expired: boolean;
            /** @default false */
            include_superseded: boolean;
            /**
             * @description "full" (default) searches the request namespace plus its ancestor/home/link cascade; "project" searches only the request namespace (no cascade); "everywhere" is "full" plus the request namespace's subtree, for the multi-agent read-shared-plus-private pattern. "exact" and "subtree" are deprecated aliases kept for back-compat: "exact" behaves as "project" (its original, pre-cascade meaning — the request namespace only) and "subtree" behaves as "everywhere". Any other value is rejected with 400.
             * @default full
             * @enum {string}
             */
            scope: "project" | "full" | "everywhere" | "exact" | "subtree";
            /** @description Search exactly these namespaces instead of the default read set (the request namespace, its subtree, and the global namespace). An entry ending in "/*" also includes namespaces nested under it. Writes are unaffected. */
            namespaces?: string[];
            /**
             * Format: date-time
             * @description Time-travel recall: return facts whose validity window contained this instant (including ones since superseded), for "what was true then" queries.
             */
            as_of?: string;
            /**
             * Format: double
             * @description Per-call relevance floor on the fused score. Candidates below it are dropped server-side before re-ranking. 0 (or unset) falls back to the server's baked relevance floor (0.1). Only meaningful with score fusion (RRF scores are not comparable to this threshold).
             */
            min_score?: number;
        };
        ScoredMemory: {
            memory: components["schemas"]["Memory"];
            /** Format: double */
            score: number;
            /** @description Read-set provenance beyond memory.namespace: omitted for a hit from the request (primary) namespace — the common case, no annotation needed — the ancestor/home namespace name itself for those two origins ("acme", "personal/kit"), and a prefixed form for a stored link or an explicit per-call namespace ("link:shared/golang", "call:acme/other"). Only populated when the read drew from a resolved read-set (recall/answer); omitted otherwise. */
            from?: string;
        };
        SearchResponse: {
            results: components["schemas"]["ScoredMemory"][];
            /** @description Set to "keyword_only" when the query embed failed or timed out and this search fell back to keyword-only matching; omitted on a healthy (vector+keyword) search. */
            degraded?: string;
            /** @description Human-readable explanation of `degraded`; omitted alongside it on a healthy search. */
            note?: string;
        };
        AnswerRequest: {
            query: string;
            tiers?: components["schemas"]["Tier"][];
            levels?: components["schemas"]["Level"][];
            /** @description Ground only on memories carrying every listed tag (AND). */
            tags?: string[];
            /** @description Ground only on memories whose top-level metadata contains every listed key=value pair (AND). */
            metadata?: {
                [key: string]: string;
            };
            /**
             * @description Caps how many recalled memories ground the answer.
             * @default 10
             */
            limit: number;
        };
        AnswerResponse: {
            answer: string;
            sources: components["schemas"]["ScoredMemory"][];
        };
        ListResponse: {
            memories: components["schemas"]["Memory"][];
        };
        Briefing: {
            namespace: string;
            /** @description A human-readable one-line summary of which namespaces this briefing drew from (its resolved read-set scope). Reserved for a future task — omitted until then. */
            scope_header?: string | null;
            /** @description Durable semantic facts, highest-retention first. */
            facts?: components["schemas"]["BriefingItem"][];
            /** @description Procedural how-to memories, highest-retention first. */
            procedures?: components["schemas"]["BriefingItem"][];
            /** @description Recent episodic activity, newest first. */
            recent?: components["schemas"]["BriefingItem"][];
            /** @description Pinned memories (any tier). */
            pinned?: components["schemas"]["BriefingItem"][];
            /** @description Per-child-namespace rollups (e.g. subtree children), each with its own pinned/recent highlights. Reserved for a future task — omitted until then. */
            children?: components["schemas"]["BriefingChild"][] | null;
        };
        BriefingItem: {
            memory: components["schemas"]["Memory"];
            /** @description Read-set provenance beyond memory.namespace — same semantics as ScoredMemory.from (see there). Omitted for a primary-namespace item. */
            from?: string;
        };
        BriefingChild: {
            namespace: string;
            /** @description Live memory count in this child namespace. */
            total: number;
            pinned?: components["schemas"]["Memory"][];
            recent?: components["schemas"]["Memory"][];
        };
        Stats: {
            namespace: string;
            /** @description Live memories (excludes expired/superseded) */
            total: number;
            by_tier: {
                [key: string]: number;
            };
            /** @description Live count per typed-extraction memory_type (decision/preference/problem). */
            by_memory_type?: {
                [key: string]: number;
            };
            expired: number;
            superseded: number;
            /** @description Live durable memories whose decayed confidence is below the demote floor — reclaimable, uncorroborated debris. */
            low_confidence_durable: number;
            total_accesses: number;
            /** Format: double */
            avg_importance: number;
            /** Format: date-time */
            last_write_at?: string | null;
        };
        NamespacesResponse: {
            namespaces: string[];
        };
        DeleteNamespaceResponse: {
            /** @description Number of memories deleted */
            deleted: number;
        };
        DeleteByTagResponse: {
            /** @description Number of memories deleted */
            deleted: number;
        };
        NamespaceLink: {
            src: string;
            dst: string;
            /** @description Tier restriction on the link; empty/omitted means the durable default (semantic, procedural). */
            tiers?: components["schemas"]["Tier"][];
            note?: string;
            /** Format: date-time */
            created_at: string;
        };
        NamespaceLinksResponse: {
            links: components["schemas"]["NamespaceLink"][];
        };
        /**
         * @description Why a namespace is in the read-set: "primary" is the request namespace (and its subtree, when expanded), "ancestor" is a path-prefix cascade leg, "home" is the caller's personal namespace, "link" is a stored namespace link, and "call" is an explicit per-call namespace.
         * @enum {string}
         */
        ReadSetOrigin: "primary" | "ancestor" | "home" | "link" | "call";
        ReadSetEntryItem: {
            namespace: string;
            origin: components["schemas"]["ReadSetOrigin"];
            /** @description Tier restriction applied to this namespace; omitted means the request's own tier filter, unrestricted beyond that. */
            tiers?: components["schemas"]["Tier"][];
        };
        ReadSetResponse: {
            entries: components["schemas"]["ReadSetEntryItem"][];
        };
        RenamespaceReport: {
            /** @description Number of memories moved. */
            moved?: number;
            /** @description Memories moved into each destination namespace. */
            targets?: {
                [key: string]: number;
            };
            /** @description Memories left in place (no grouping key, or already in place). */
            skipped?: number;
            /** @description Whether this was a dry run. */
            dry_run?: boolean;
        };
        FsckReport: {
            expired_purged: number;
            short_term_evicted: number;
            namespaces: number;
            duplicate_groups?: string[][];
        };
        /**
         * @description Optional knobs for one dedup pass. The zero value uses the production
         *     defaults (similarity 0.85, cluster size ≥ 2, all tiers, 20 neighbours
         *     per anchor, dry_run false), scoped to the request's namespace.
         */
        DedupRequest: {
            /**
             * Format: double
             * @description Cosine-like threshold for cluster membership. Higher = stricter
             *     (fewer, tighter clusters). 0 falls back to 0.85.
             */
            similarity?: number;
            /** @description Smallest cluster acted on. 0 falls back to 2. */
            min_cluster_size?: number;
            /** @description Restrict the pass to these tiers; empty means all. */
            tiers?: components["schemas"]["Tier"][];
            /** @description Per-anchor vector-search fan-out. 0 falls back to 20. */
            neighbours_per_anchor?: number;
            /**
             * @description Run the pass over every namespace instead of just the request's
             *     namespace. Defaults to false (scope to the request namespace).
             */
            all_namespaces?: boolean;
            /** @description Report what would happen without tombstoning anything. */
            dry_run?: boolean;
        };
        DedupReport: {
            namespaces: number;
            memories_seen: number;
            clusters_found: number;
            tombstoned: number;
            dry_run: boolean;
            /** @description Per-cluster representative selection. Omitted when no clusters were found. */
            actions?: components["schemas"]["ClusterAction"][];
        };
        ClusterAction: {
            representative_id: string;
            tombstoned_ids: string[];
            size: number;
        };
        Memory: {
            id: string;
            namespace: string;
            tier: components["schemas"]["Tier"];
            /** @description Derivation provenance: explicit (user-stated / heuristic) vs deduced (LLM-distilled). Null/omitted when the row predates the tag or when unset. */
            level?: components["schemas"]["Level"];
            content: string;
            summary?: string;
            metadata?: {
                [key: string]: unknown;
            };
            tags?: string[];
            /** Format: double */
            importance: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_accessed_at: string;
            access_count: number;
            /** Format: date-time */
            expires_at?: string | null;
            superseded_by?: string | null;
            /**
             * Format: date-time
             * @description Start of the wall-clock interval the fact was true; null means open ("always, until valid_to"). Used by time-travel (as_of) recall.
             */
            valid_from?: string | null;
            /**
             * Format: date-time
             * @description End of the interval the fact was true; null means open ("still true"). Stamped automatically when a fact is superseded.
             */
            valid_to?: string | null;
            /**
             * Format: double
             * @description Corroboration of a durable fact in [0,1]; null when not tracked.
             */
            confidence?: number | null;
            /** @description Optional. Present only on POST /v1/memories responses when the write's nearest same-tier candidate scored at/above MEMINI_WRITE_DEDUP_SCORE and MEMINI_WRITE_DEDUP_ACTION is "hint". */
            merge_hint?: components["schemas"]["MergeHint"];
            /** @description Optional. Present only on POST /v1/memories responses when the write's nearest same-tier candidate scored at/above MEMINI_WRITE_DEDUP_SCORE with MEMINI_WRITE_DEDUP_ACTION="supersede" and the old memory was tombstoned in the background. The caller still receives the new memory. */
            auto_superseded?: boolean;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: string;
                };
            };
        };
    };
    parameters: {
        /** @description Tenant/agent namespace; falls back to the server default. */
        Namespace: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics in Prometheus text format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    runFsck: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsckReport"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    runDedup: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DedupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupReport"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    listMemories: {
        parameters: {
            query?: {
                /** @description Repeatable and/or comma-separated tier filter; omitted means all tiers. */
                tier?: components["schemas"]["Tier"][];
                /** @description Repeatable and/or comma-separated level filter; omitted means all levels. */
                level?: components["schemas"]["Level"][];
                /** @description Repeatable and/or comma-separated tag filter; a memory must carry every listed tag (AND). */
                tag?: string[];
                /** @description Repeatable metadata filter in "key=value" form; a memory's top-level metadata must contain every listed pair (AND). Only string values match. */
                meta?: string[];
                include_expired?: boolean;
                include_superseded?: boolean;
                /** @description Caps the result count; 0 or absent returns all matches. */
                limit?: number;
                /** @description Aggregate across every namespace, ignoring the namespace header. The server merges all namespaces and applies limit as a single global cap (newest first), so the admin UI's "All projects" view fetches one response instead of one request per namespace. */
                all_namespaces?: boolean;
            };
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    rememberMemory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RememberRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    forgetByTag: {
        parameters: {
            query: {
                /** @description Exact tag a memory must carry to be deleted. */
                tag: string;
            };
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteByTagResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getStats: {
        parameters: {
            query?: {
                /** @description Aggregate counts across every namespace, ignoring the namespace header. Returns a single merged overview (namespace reported as "") so the admin UI's "All projects" view fetches one response instead of one request per namespace. */
                all_namespaces?: boolean;
            };
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    listNamespaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamespacesResponse"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    deleteNamespace: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteNamespaceResponse"];
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getBriefing: {
        parameters: {
            query?: {
                /** @description Default cap applied to every section when its dedicated cap is unset. Default 5. */
                per_section?: number;
                /** @description Max pinned memories. Overrides per_section. 0 disables the section. */
                per_section_pinned?: number;
                /** @description Max durable semantic facts. Overrides per_section. 0 disables the section. */
                per_section_facts?: number;
                /** @description Max procedural how-to memories. Overrides per_section. 0 disables the section. */
                per_section_procedures?: number;
                /** @description Max recent episodic entries. Overrides per_section. 0 disables the section. */
                per_section_recent?: number;
                /** @description "full" (default) briefs the namespace plus its ancestor/home/link cascade; "project" briefs only the namespace (no cascade); "everywhere" is "full" plus namespaces nested under it ("project" also reads "project/agent"). "exact" and "subtree" are deprecated aliases kept for back-compat: "exact" behaves as "project" (its original, pre-cascade meaning) and "subtree" behaves as "everywhere". Any other value is rejected with 400. */
                scope?: "project" | "full" | "everywhere" | "exact" | "subtree";
                /** @description Repeatable. Brief exactly these namespaces instead of the default read set (the namespace, its subtree, and the global namespace). An entry ending in "/*" also includes namespaces nested under it. Writes are unaffected. */
                namespaces?: string[];
            };
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Briefing"];
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getReadSet: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadSetResponse"];
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    listLinks: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamespaceLinksResponse"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    putLink: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Target namespace. */
                    dst: string;
                    /** @description Restrict which tiers cross the link; empty/omitted means the durable default (semantic, procedural) — non-durable tiers never cross a link regardless. */
                    tiers?: components["schemas"]["Tier"][];
                    /** @description Free-text annotation for operators. */
                    note?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamespaceLink"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    deleteLink: {
        parameters: {
            query?: {
                /** @description Target namespace to unlink. Required, via query or JSON body. */
                dst?: string;
            };
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Target namespace to unlink. */
                    dst?: string;
                };
            };
        };
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    moveNamespace: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Target namespace. */
                    to: string;
                    /** @default false */
                    dry_run?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamespaceReport"];
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    splitNamespace: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Metadata keys to group by. Defaults to import_source_namespace, user_id, agent_id, run_id, project. */
                    by?: string[];
                    /** @default false */
                    dry_run?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamespaceReport"];
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    reassignMemory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Target namespace. */
                    to: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Always 1 (a missing memory is a 404, not moved=0). */
                        moved?: number;
                    };
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getMemory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    forgetMemory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    getMemoryHistory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    supersedeMemory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupersedeRequest"];
            };
        };
        responses: {
            /** @description Superseded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    searchMemories: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
}
