/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (verifies storage backend) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Protected by bearer auth when MEMINI_API_KEY is set; unauthenticated otherwise.
         */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fsck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a consistency sweep (purge expired, enforce short-term cap, audit duplicates) */
        post: operations["runFsck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dedup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Collapse near-duplicate memories (vector cluster) — tombstone the lower-scored members of each cluster
         * @description Clusters live memories by embedding similarity (cosine ≥
         *     `similarity`) and tombstones the lower-RetentionScore members of each
         *     cluster, pointing them at the cluster's representative. The action is
         *     reversible (SupersededBy → representative) and the duplicates remain in
         *     storage but are hidden from default search results. Dry-run reports the
         *     actions without committing them.
         *
         *     Scoped to the request's namespace by default — the common case is
         *     cleaning up right after a large import into one namespace, where
         *     exports are typically full of restatements. Set `all_namespaces: true`
         *     to run the pass over every namespace instead.
         */
        post: operations["runDedup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List memories in a namespace (backs the admin UI browser) */
        get: operations["listMemories"];
        put?: never;
        /** Remember (store) a memory */
        post: operations["rememberMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-namespace overview (counts by tier, accesses, importance) */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the distinct namespaces holding memories */
        get: operations["listNamespaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/namespaces/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete every memory in a namespace */
        delete: operations["deleteNamespace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Fetch a memory by ID */
        get: operations["getMemory"];
        put?: never;
        post?: never;
        /** Forget (delete) a memory */
        delete: operations["forgetMemory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recall memories via hybrid (vector + keyword) search */
        post: operations["searchMemories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recall memories and answer a question grounded on them (requires an LLM) */
        post: operations["answerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Tier: "working" | "episodic" | "semantic" | "procedural";
        RememberRequest: {
            content: string;
            tier?: components["schemas"]["Tier"];
            summary?: string;
            tags?: string[];
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: double */
            importance?: number;
            /** @description Overrides the tier default TTL; negative means never expire. */
            ttl_seconds?: number;
            /** @description Upserts an existing memory when provided. */
            id?: string;
        };
        SearchRequest: {
            query: string;
            tiers?: components["schemas"]["Tier"][];
            /** @default 10 */
            limit: number;
            /** @default false */
            include_expired: boolean;
            /** @default false */
            include_superseded: boolean;
        };
        ScoredMemory: {
            memory: components["schemas"]["Memory"];
            /** Format: double */
            score: number;
        };
        SearchResponse: {
            results: components["schemas"]["ScoredMemory"][];
        };
        AnswerRequest: {
            query: string;
            tiers?: components["schemas"]["Tier"][];
            /**
             * @description Caps how many recalled memories ground the answer.
             * @default 10
             */
            limit: number;
        };
        AnswerResponse: {
            answer: string;
            sources: components["schemas"]["ScoredMemory"][];
        };
        ListResponse: {
            memories: components["schemas"]["Memory"][];
        };
        Stats: {
            namespace: string;
            /** @description Live memories (excludes expired/superseded) */
            total: number;
            by_tier: {
                [key: string]: number;
            };
            expired: number;
            superseded: number;
            total_accesses: number;
            /** Format: double */
            avg_importance: number;
            /** Format: date-time */
            last_write_at?: string | null;
        };
        NamespacesResponse: {
            namespaces: string[];
        };
        DeleteNamespaceResponse: {
            /** @description Number of memories deleted */
            deleted: number;
        };
        FsckReport: {
            expired_purged: number;
            short_term_evicted: number;
            namespaces: number;
            duplicate_groups?: string[][];
        };
        /**
         * @description Optional knobs for one dedup pass. The zero value uses the production
         *     defaults (similarity 0.85, cluster size ≥ 2, all tiers, 20 neighbours
         *     per anchor, dry_run false), scoped to the request's namespace.
         */
        DedupRequest: {
            /**
             * Format: double
             * @description Cosine-like threshold for cluster membership. Higher = stricter
             *     (fewer, tighter clusters). 0 falls back to 0.85.
             */
            similarity?: number;
            /** @description Smallest cluster acted on. 0 falls back to 2. */
            min_cluster_size?: number;
            /** @description Restrict the pass to these tiers; empty means all. */
            tiers?: components["schemas"]["Tier"][];
            /** @description Per-anchor vector-search fan-out. 0 falls back to 20. */
            neighbours_per_anchor?: number;
            /**
             * @description Run the pass over every namespace instead of just the request's
             *     namespace. Defaults to false (scope to the request namespace).
             */
            all_namespaces?: boolean;
            /** @description Report what would happen without tombstoning anything. */
            dry_run?: boolean;
        };
        DedupReport: {
            namespaces: number;
            memories_seen: number;
            clusters_found: number;
            tombstoned: number;
            dry_run: boolean;
            /** @description Per-cluster representative selection. Omitted when no clusters were found. */
            actions?: components["schemas"]["ClusterAction"][];
        };
        ClusterAction: {
            representative_id: string;
            tombstoned_ids: string[];
            size: number;
        };
        Memory: {
            id: string;
            namespace: string;
            tier: components["schemas"]["Tier"];
            content: string;
            summary?: string;
            metadata?: {
                [key: string]: unknown;
            };
            tags?: string[];
            /** Format: double */
            importance: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_accessed_at: string;
            access_count: number;
            /** Format: date-time */
            expires_at?: string | null;
            superseded_by?: string | null;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: string;
                };
            };
        };
    };
    parameters: {
        /** @description Tenant/agent namespace; falls back to the server default. */
        Namespace: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics in Prometheus text format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    runFsck: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsckReport"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    runDedup: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DedupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupReport"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    listMemories: {
        parameters: {
            query?: {
                /** @description Repeatable and/or comma-separated tier filter; omitted means all tiers. */
                tier?: components["schemas"]["Tier"][];
                include_expired?: boolean;
                include_superseded?: boolean;
                /** @description Caps the result count; 0 or absent returns all matches. */
                limit?: number;
            };
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    rememberMemory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RememberRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    listNamespaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamespacesResponse"];
                };
            };
            500: components["responses"]["Error"];
        };
    };
    deleteNamespace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteNamespaceResponse"];
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getMemory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Memory"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    forgetMemory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    searchMemories: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    answerQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Tenant/agent namespace; falls back to the server default. */
                "X-Memini-Namespace"?: components["parameters"]["Namespace"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
}
