use anyhow::{Context, Result, bail};
use clap::Command;
use serde::Deserialize;
use serde_json::Value;
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    path::Path,
};

pub fn generate(command: Command, cli_path: &Path) -> Result<()> {
    let reference_dir = cli_path
        .parent()
        .context("CLI reference path must have a parent directory")?;
    std::fs::create_dir_all(reference_dir)?;
    std::fs::write(cli_path, render_cli(command))?;
    std::fs::write(reference_dir.join("mcp-tools.md"), render_mcp())?;
    std::fs::write(
        reference_dir.join("rest-api.md"),
        render_rest(Path::new("api/openapi.yaml"))?,
    )?;
    validate_configuration(&reference_dir.join("configuration.md"))?;
    Ok(())
}

fn render_cli(command: Command) -> String {
    fn visit(command: &Command, prefix: &str, output: &mut String) {
        for child in command
            .get_subcommands()
            .filter(|child| !matches!(child.get_name(), "help" | "gen-docs"))
        {
            let full = format!("{prefix} {}", child.get_name());
            let _ = write!(output, "\n## `{full}`\n\n");
            if let Some(about) = child.get_about() {
                let _ = write!(output, "{about}\n\n");
            }
            let mut rendered = child.clone();
            output.push_str("```text\n");
            for line in rendered.render_help().to_string().lines() {
                let _ = writeln!(output, "{}", line.trim_end());
            }
            output.push_str("```\n");
            visit(child, &full, output);
        }
    }
    let mut output = "<!-- Generated by the Rust `memini gen-docs` command. DO NOT EDIT. -->\n<!-- Regenerate with: mise run docs -->\n\n# CLI reference\n".to_owned();
    visit(&command, "memini", &mut output);
    output
}

fn render_mcp() -> String {
    let base: BTreeSet<String> = memini_api::mcp_tools(false)
        .iter()
        .filter_map(|tool| tool["name"].as_str().map(str::to_owned))
        .collect();
    let order = [
        "memory_briefing",
        "memory_recall",
        "memory_remember",
        "memory_answer",
        "memory_list",
        "memory_get",
        "memory_history",
        "memory_update",
        "memory_forget",
    ];
    let mut tools = memini_api::mcp_tools(true);
    tools.sort_by_key(|tool| {
        order
            .iter()
            .position(|name| tool["name"] == *name)
            .unwrap_or(order.len())
    });

    let mut out = "<!-- Generated by the Rust `memini gen-docs` command from the runtime MCP definitions. DO NOT EDIT. -->\n<!-- Regenerate with: mise run docs -->\n\n# MCP tools\n\nThe tools an agent sees when it connects to memini, generated from the same definitions returned by `tools/list`.\n\n- **Streamable HTTP**, at `http://<host>:8080/mcp`, for a shared always-on server.\n- **stdio**, via `memini mcp`, for a server the agent spawns per session.\n\n## The tools\n\n| Tool | Does | Available |\n| --- | --- | --- |\n".to_owned();
    for tool in &tools {
        let name = tool["name"].as_str().unwrap_or_default();
        let title = tool["title"].as_str().unwrap_or_default();
        let available = if base.contains(name) {
            "always"
        } else {
            "**only with an LLM configured**"
        };
        let _ = writeln!(out, "| [`{name}`](#{name}) | {title} | {available} |");
    }
    out.push_str("\n`memory_answer` is only registered when `MEMINI_LLM_BASE_URL` is set.\n\n## Server instructions\n\n```text\n");
    out.push_str(memini_api::MCP_SERVER_INSTRUCTIONS);
    out.push_str("\n```\n");

    for tool in &tools {
        let name = tool["name"].as_str().unwrap_or_default();
        let annotations = &tool["annotations"];
        let kind = if annotations["destructiveHint"] == true {
            "destructive"
        } else if annotations["readOnlyHint"] == true {
            "read-only"
        } else {
            "additive"
        };
        let _ = write!(
            out,
            "\n## `{name}`\n\n*{kind}*\n\n{}\n\n",
            tool["description"].as_str().unwrap_or_default()
        );
        let Some(properties) = tool["inputSchema"]["properties"].as_object() else {
            continue;
        };
        if properties.is_empty() {
            out.push_str("No parameters.\n");
            continue;
        }
        let required: BTreeSet<&str> = tool["inputSchema"]["required"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
            .collect();
        let sorted: BTreeMap<&str, &Value> = properties
            .iter()
            .map(|(name, schema)| (name.as_str(), schema))
            .collect();
        out.push_str("| Parameter | Type | Required | Description |\n| --- | --- | --- | --- |\n");
        for (param, schema) in sorted {
            let type_name = schema["type"].as_str().unwrap_or("any");
            let type_name = if type_name == "array" {
                format!("{}[]", schema["items"]["type"].as_str().unwrap_or("any"))
            } else {
                type_name.to_owned()
            };
            let mut description = schema["description"]
                .as_str()
                .unwrap_or_default()
                .replace('|', "\\|")
                .replace('\n', " ");
            let enums = schema["enum"]
                .as_array()
                .or_else(|| schema["items"]["enum"].as_array());
            if let Some(enums) = enums {
                let values = enums
                    .iter()
                    .filter_map(Value::as_str)
                    .map(|value| format!("`{value}`"))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = write!(description, " One of {values}.");
            }
            let yes = if required.contains(param) { "yes" } else { "" };
            let _ = writeln!(out, "| `{param}` | {type_name} | {yes} | {description} |");
        }
    }
    out
}

#[derive(Deserialize)]
struct OpenApi {
    paths: BTreeMap<String, BTreeMap<String, serde_yaml::Value>>,
}

#[derive(Deserialize, Default)]
struct Operation {
    #[serde(default)]
    summary: String,
    #[serde(default)]
    description: String,
}

struct RestGroup {
    title: &'static str,
    intro: &'static str,
    prefixes: &'static [&'static str],
}

const REST_GROUPS: &[RestGroup] = &[
    RestGroup {
        title: "Memories",
        intro: "The core read and write surface. `POST /v1/search` is the REST equivalent of `memory_recall`.",
        prefixes: &["/v1/memories", "/v1/search", "/v1/answer"],
    },
    RestGroup {
        title: "Namespaces and scoping",
        intro: "Inspect and repair how memories are partitioned.",
        prefixes: &["/v1/namespaces", "/v1/links"],
    },
    RestGroup {
        title: "Maintenance",
        intro: "Run hygiene passes on demand rather than waiting for the background schedule.",
        prefixes: &["/v1/dedup", "/v1/fsck", "/v1/stats", "/v1/activity"],
    },
    RestGroup {
        title: "API keys",
        intro: "Requires the admin key (`MEMINI_API_KEY`).",
        prefixes: &["/v1/keys"],
    },
    RestGroup {
        title: "Operational",
        intro: "Health, readiness, and Prometheus metrics endpoints.",
        prefixes: &["/healthz", "/readyz", "/metrics"],
    },
];

fn render_rest(spec_path: &Path) -> Result<String> {
    let spec: OpenApi = serde_yaml::from_slice(
        &std::fs::read(spec_path).with_context(|| format!("reading {}", spec_path.display()))?,
    )?;
    let methods = ["get", "post", "put", "patch", "delete", "head", "options"];
    let mut grouped: BTreeMap<&str, Vec<(String, String, String)>> = BTreeMap::new();
    for (path, operations) in spec.paths {
        let group = REST_GROUPS
            .iter()
            .find(|group| {
                group
                    .prefixes
                    .iter()
                    .any(|prefix| path == *prefix || path.starts_with(&format!("{prefix}/")))
            })
            .with_context(|| format!("OpenAPI path {path} belongs to no docs section"))?;
        for (method, value) in operations {
            if !methods.contains(&method.as_str()) {
                continue;
            }
            let operation: Operation = serde_yaml::from_value(value)?;
            let summary = if operation.summary.is_empty() {
                operation.description
            } else {
                operation.summary
            };
            grouped.entry(group.title).or_default().push((
                method.to_uppercase(),
                path.clone(),
                summary.replace('|', "\\|").replace('\n', " "),
            ));
        }
    }
    let mut out = "<!-- Generated by the Rust `memini gen-docs` command from api/openapi.yaml. DO NOT EDIT. -->\n<!-- Regenerate with: mise run docs -->\n\n# REST API\n\nEvery endpoint the server exposes, indexed from [`api/openapi.yaml`](../../api/openapi.yaml).\n\nEvery route takes its namespace from `X-Memini-Namespace`; the caller's personal namespace travels in `X-Memini-Home`.\n".to_owned();
    for group in REST_GROUPS {
        let Some(rows) = grouped.get_mut(group.title) else {
            continue;
        };
        rows.sort();
        let _ = write!(
            out,
            "\n## {}\n\n{}\n\n| Endpoint | Does |\n| --- | --- |\n",
            group.title, group.intro
        );
        for (method, path, summary) in rows {
            let _ = writeln!(out, "| `{method} {path}` | {summary} |");
        }
    }
    Ok(out)
}

fn validate_configuration(path: &Path) -> Result<()> {
    let mut document =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    for (name, default) in memini_config::config::CONFIG_VARIABLES {
        let rendered_default = if default.is_empty() {
            "none".to_owned()
        } else {
            format!("`{default}`")
        };
        let row_prefix = format!("| [`{name}`]");
        let heading = format!("### `{name}`");
        if !document.lines().any(|line| {
            line.starts_with(&row_prefix) && line.contains(&format!("| {rendered_default} |"))
        }) || !document.contains(&heading)
        {
            bail!("configuration reference is missing {name} or documents the wrong default");
        }
    }
    if let Some(newline) = document.find('\n') {
        document.replace_range(
            ..newline,
            "<!-- Validated by the Rust `memini gen-docs` command against memini-config. -->",
        );
    }
    std::fs::write(path, document)?;
    Ok(())
}
