//go:build gendocs

// The CLI reference is generated by walking the cobra command tree, which lives
// in package main and so cannot be imported from cmd/gendocs. A build-tagged
// subcommand is the way in: it has full access to rootCmd, and it is compiled
// out of the shipped binary entirely.
//
// Run it through `mise run docs`, not by hand.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

var gendocsOut string

func init() {
	cmd := &cobra.Command{
		Use:    "gen-docs",
		Short:  "Write the CLI reference (build-tagged; not in the shipped binary)",
		Hidden: true,
		RunE: func(_ *cobra.Command, _ []string) error {
			var b strings.Builder
			b.WriteString("<!-- Generated by `mise run docs` from the cobra command tree. DO NOT EDIT. -->\n\n")
			b.WriteString("# CLI reference\n\n")
			b.WriteString("Every command the `memini` binary accepts. Running `memini` with no arguments starts\n")
			b.WriteString("the server; everything else is an operational subcommand.\n\n")
			b.WriteString("The server is configured entirely through the environment rather than flags, so the\n")
			b.WriteString("flags below belong to the subcommands only. See the\n")
			b.WriteString("[configuration reference](configuration.md) for the environment.\n\n")

			b.WriteString("## Commands\n\n| Command | Does |\n| --- | --- |\n")
			walk(rootCmd, func(c *cobra.Command, path string) {
				if c == rootCmd {
					return
				}
				fmt.Fprintf(&b, "| [`memini %s`](#memini-%s) | %s |\n",
					path, strings.ReplaceAll(path, " ", "-"), cell(c.Short))
			})
			b.WriteString("\n")

			walk(rootCmd, func(c *cobra.Command, path string) {
				if c == rootCmd {
					return
				}
				fmt.Fprintf(&b, "## `memini %s`\n\n", path)
				if c.Long != "" {
					b.WriteString(esc(c.Long) + "\n\n")
				} else if c.Short != "" {
					b.WriteString(esc(c.Short) + "\n\n")
				}
				fmt.Fprintf(&b, "```\nmemini %s\n```\n\n", c.UseLine()[len(rootCmd.Name())+1:])

				var rows []string
				c.LocalFlags().VisitAll(func(f *pflag.Flag) {
					if f.Hidden {
						return
					}
					dflt := ""
					if f.DefValue != "" && f.DefValue != "false" && f.DefValue != "[]" {
						dflt = "`" + f.DefValue + "`"
					}
					rows = append(rows, fmt.Sprintf("| `--%s` | %s | %s |", f.Name, dflt, cell(f.Usage)))
				})
				if len(rows) > 0 {
					b.WriteString("| Flag | Default | Does |\n| --- | --- | --- |\n")
					b.WriteString(strings.Join(rows, "\n") + "\n\n")
				}
			})

			if err := os.MkdirAll(filepath.Dir(gendocsOut), 0o755); err != nil {
				return err
			}
			return os.WriteFile(gendocsOut, []byte(b.String()), 0o644)
		},
	}
	cmd.Flags().StringVar(&gendocsOut, "out", "docs/reference/cli.md", "output path")
	rootCmd.AddCommand(cmd)
}

// esc protects the angle-bracket placeholders that appear throughout the
// command help ("<tenant>/_shared", "<name>"), which a markdown renderer would
// otherwise swallow as HTML tags. Text already inside backticks is left alone.
func esc(s string) string {
	var b strings.Builder
	inCode := false
	for _, r := range s {
		switch {
		case r == '`':
			inCode = !inCode
			b.WriteRune(r)
		case r == '<' && !inCode:
			b.WriteString("&lt;")
		case r == '>' && !inCode:
			b.WriteString("&gt;")
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// cell additionally flattens text so it cannot break out of a table row.
func cell(s string) string {
	return strings.ReplaceAll(esc(strings.Join(strings.Fields(s), " ")), "|", `\|`)
}

// walk visits the command tree depth-first in the order the commands are
// declared, so parents appear before their subcommands.
func walk(c *cobra.Command, fn func(*cobra.Command, string)) {
	var rec func(*cobra.Command, string)
	rec = func(cur *cobra.Command, prefix string) {
		path := strings.TrimSpace(prefix + " " + name(cur))
		if cur == rootCmd {
			path = ""
		}
		fn(cur, path)
		for _, sub := range cur.Commands() {
			if sub.Hidden || sub.Name() == "help" || sub.Name() == "completion" {
				continue
			}
			rec(sub, path)
		}
	}
	rec(c, "")
}

// name is the command word, stripped of any argument placeholders in Use
// ("key add <name>" is the "add" command).
func name(c *cobra.Command) string {
	if c == rootCmd {
		return ""
	}
	return strings.Fields(c.Use)[0]
}
